// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	"comment/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/comments",
				Handler: AddHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/comments",
				Handler: DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/comments",
				Handler: listHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/comments/:id",
				Handler: GetHandler(serverCtx),
			},
		},
	)
}
