// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: history.proto

package server

import (
	"context"

	"history/rpc/history"
	"history/rpc/internal/logic"
	"history/rpc/internal/svc"
)

type HistoryServer struct {
	svcCtx *svc.ServiceContext
	history.UnimplementedHistoryServer
}

func NewHistoryServer(svcCtx *svc.ServiceContext) *HistoryServer {
	return &HistoryServer{
		svcCtx: svcCtx,
	}
}

func (s *HistoryServer) RecordHistory(ctx context.Context, in *history.RecordHistoryRequest) (*history.RecordHistoryResponse, error) {
	l := logic.NewRecordHistoryLogic(ctx, s.svcCtx)
	return l.RecordHistory(in)
}

func (s *HistoryServer) ListHistory(ctx context.Context, in *history.ListHistoryRequest) (*history.ListHistoryResponse, error) {
	l := logic.NewListHistoryLogic(ctx, s.svcCtx)
	return l.ListHistory(in)
}

func (s *HistoryServer) DeleteHistoryItem(ctx context.Context, in *history.DeleteHistoryItemRequest) (*history.ActionResponse, error) {
	l := logic.NewDeleteHistoryItemLogic(ctx, s.svcCtx)
	return l.DeleteHistoryItem(in)
}

func (s *HistoryServer) ClearHistoryByType(ctx context.Context, in *history.ClearHistoryByTypeRequest) (*history.ActionResponse, error) {
	l := logic.NewClearHistoryByTypeLogic(ctx, s.svcCtx)
	return l.ClearHistoryByType(in)
}

func (s *HistoryServer) ClearHistoryAll(ctx context.Context, in *history.ClearHistoryAllRequest) (*history.ActionResponse, error) {
	l := logic.NewClearHistoryAllLogic(ctx, s.svcCtx)
	return l.ClearHistoryAll(in)
}
