apiVersion: apps/v1
kind: Deployment
metadata:
  name: userrpc
  namespace: user
  labels:
    app: userrpc
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: userrpc
  template:
    metadata:
      labels:
        app: userrpc
    spec:
      containers:
      - name: userrpc
        image: userrpc:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9001
        readinessProbe:
          tcpSocket:
            port: 9001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 9001
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
        - name: config-volume
          mountPath: /app/etc
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: config-volume
          hostPath:
            path: /home/jerry/learnspace/go/src/game/server/code/common/service/user/rpc/etc # 你主机上的配置文件目录
            type: DirectoryOrCreate

---

apiVersion: v1
kind: Service
metadata:
  name: userrpc-svc
  namespace: user
spec:
  ports:
  - port: 9001
    targetPort: 9001
  selector:
    app: userrpc
  type: ClusterIP
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: userrpc-hpa-c
  namespace: user
  labels:
    app: userrpc-hpa-c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: userrpc
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: userrpc-hpa-m
  namespace: user
  labels:
    app: userrpc-hpa-m
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: userrpc
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
