package errx

const (
	CodeBadRequestDefault = "U1000"
	CodeInternalDefault   = "U5000"

	CodeMobileRequired             = "U1001"
	CodePasswordRequired           = "U1002"
	CodeNameRequired               = "U1003"
	CodeUIDInvalid                 = "U1004"
	CodeChangePasswordRequired     = "U1005"
	CodePasswordMustDiffer         = "U1006"
	CodeNewPasswordTooShort        = "U1007"
	CodeNewMobileRequired          = "U1008"
	CodeVerifyCodeRequired         = "U1009"
	CodeBindEmailRequired          = "U1010"
	CodeEmailRequired              = "U1011"
	CodeAvatarTooLong              = "U1012"
	CodeBioTooLong                 = "U1013"
	CodeLocationTooLong            = "U1014"
	CodeBirthdayFormatInvalid      = "U1015"
	CodeUnauthorized               = "U2003"
	CodeRiskRejected               = "U3001"
	CodeOldPasswordIncorrect       = "U3002"
	CodeVerifyCodeInvalidOrExpired = "U3003"
	CodeMobileAlreadyInUse         = "U3004"
	CodeEmailAlreadyInUse          = "U3005"
	CodeRateLimited                = "U4001"
	CodeLoginFailed                = "U5001"
	CodeUserQueryFailed            = "U5002"
	CodeUserUpdateFailed           = "U5003"
	CodeSMSVerifierUnavailable     = "U5004"
	CodeMobileIndexQueryFailed     = "U5005"
	CodeEmailVerifierUnavailable   = "U5006"
	CodeEmailIndexQueryFailed      = "U5007"
	CodeProfileModelUnavailable    = "U5008"
	CodeProfileUpsertFailed        = "U5009"
)
