// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: friend.proto

package server

import (
	"context"

	"friend/rpc/friend"
	"friend/rpc/internal/logic"
	"friend/rpc/internal/svc"
)

type FriendServer struct {
	svcCtx *svc.ServiceContext
	friend.UnimplementedFriendServer
}

func NewFriendServer(svcCtx *svc.ServiceContext) *FriendServer {
	return &FriendServer{
		svcCtx: svcCtx,
	}
}

// 好友申请
func (s *FriendServer) SendRequest(ctx context.Context, in *friend.SendRequestReq) (*friend.SendRequestResp, error) {
	l := logic.NewSendRequestLogic(ctx, s.svcCtx)
	return l.SendRequest(in)
}

func (s *FriendServer) AcceptRequest(ctx context.Context, in *friend.AcceptRequestReq) (*friend.AcceptRequestResp, error) {
	l := logic.NewAcceptRequestLogic(ctx, s.svcCtx)
	return l.AcceptRequest(in)
}

func (s *FriendServer) RejectRequest(ctx context.Context, in *friend.RejectRequestReq) (*friend.RejectRequestResp, error) {
	l := logic.NewRejectRequestLogic(ctx, s.svcCtx)
	return l.RejectRequest(in)
}

func (s *FriendServer) ListRequests(ctx context.Context, in *friend.ListRequestsReq) (*friend.ListRequestsResp, error) {
	l := logic.NewListRequestsLogic(ctx, s.svcCtx)
	return l.ListRequests(in)
}

// 好友管理
func (s *FriendServer) RemoveFriend(ctx context.Context, in *friend.RemoveFriendReq) (*friend.RemoveFriendResp, error) {
	l := logic.NewRemoveFriendLogic(ctx, s.svcCtx)
	return l.RemoveFriend(in)
}

func (s *FriendServer) ListFriends(ctx context.Context, in *friend.ListFriendsReq) (*friend.ListFriendsResp, error) {
	l := logic.NewListFriendsLogic(ctx, s.svcCtx)
	return l.ListFriends(in)
}

func (s *FriendServer) CheckFriendship(ctx context.Context, in *friend.CheckFriendshipReq) (*friend.CheckFriendshipResp, error) {
	l := logic.NewCheckFriendshipLogic(ctx, s.svcCtx)
	return l.CheckFriendship(in)
}

// 黑名单
func (s *FriendServer) BlockUser(ctx context.Context, in *friend.BlockUserReq) (*friend.BlockUserResp, error) {
	l := logic.NewBlockUserLogic(ctx, s.svcCtx)
	return l.BlockUser(in)
}

func (s *FriendServer) UnblockUser(ctx context.Context, in *friend.UnblockUserReq) (*friend.UnblockUserResp, error) {
	l := logic.NewUnblockUserLogic(ctx, s.svcCtx)
	return l.UnblockUser(in)
}

func (s *FriendServer) ListBlockedUsers(ctx context.Context, in *friend.ListBlockedUsersReq) (*friend.ListBlockedUsersResp, error) {
	l := logic.NewListBlockedUsersLogic(ctx, s.svcCtx)
	return l.ListBlockedUsers(in)
}
