services:
  prometheus:
    build:
      context: ./deploy/docker/prometheus
    environment:
      - TZ=${TZ}
    volumes:
      - ./deploy/docker/prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT}:9090"
    networks:
      - backend
    restart: always

  grafana:
    build:
      context: ./deploy/docker/grafana
    environment:
      - TZ=${TZ}
    ports:
      - "${GRAFANA_PORT}:3000"
    networks:
      - backend
    restart: always

  jaeger:
    build:
      context: ./deploy/docker/jaeger
    environment:
      - TZ=${TZ}
    ports:
      - "${JAEGER_PORT}:16686"
      - "14268:14268"
    networks:
      - backend
    restart: always
