// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rpc/vda.proto

package vda

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=Domain,proto3" json:"Domain,omitempty"`
	TenantID      string                 `protobuf:"bytes,3,opt,name=TenantID,proto3" json:"TenantID,omitempty"`
	ProjectID     string                 `protobuf:"bytes,4,opt,name=ProjectID,proto3" json:"ProjectID,omitempty"`
	Environment   string                 `protobuf:"bytes,5,opt,name=Environment,proto3" json:"Environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallerInfo) Reset() {
	*x = CallerInfo{}
	mi := &file_rpc_vda_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallerInfo) ProtoMessage() {}

func (x *CallerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_vda_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallerInfo.ProtoReflect.Descriptor instead.
func (*CallerInfo) Descriptor() ([]byte, []int) {
	return file_rpc_vda_proto_rawDescGZIP(), []int{0}
}

func (x *CallerInfo) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *CallerInfo) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CallerInfo) GetTenantID() string {
	if x != nil {
		return x.TenantID
	}
	return ""
}

func (x *CallerInfo) GetProjectID() string {
	if x != nil {
		return x.ProjectID
	}
	return ""
}

func (x *CallerInfo) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

type InitiateCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Caller        *CallerInfo            `protobuf:"bytes,1,opt,name=Caller,proto3" json:"Caller,omitempty"`
	Callee        int64                  `protobuf:"varint,2,opt,name=Callee,proto3" json:"Callee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateCallRequest) Reset() {
	*x = InitiateCallRequest{}
	mi := &file_rpc_vda_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateCallRequest) ProtoMessage() {}

func (x *InitiateCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_vda_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateCallRequest.ProtoReflect.Descriptor instead.
func (*InitiateCallRequest) Descriptor() ([]byte, []int) {
	return file_rpc_vda_proto_rawDescGZIP(), []int{1}
}

func (x *InitiateCallRequest) GetCaller() *CallerInfo {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *InitiateCallRequest) GetCallee() int64 {
	if x != nil {
		return x.Callee
	}
	return 0
}

type InitiateCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallID        string                 `protobuf:"bytes,1,opt,name=CallID,proto3" json:"CallID,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=State,proto3" json:"State,omitempty"`
	LiveKitRoom   string                 `protobuf:"bytes,3,opt,name=LiveKitRoom,proto3" json:"LiveKitRoom,omitempty"`
	LiveKitToken  string                 `protobuf:"bytes,4,opt,name=LiveKitToken,proto3" json:"LiveKitToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateCallResponse) Reset() {
	*x = InitiateCallResponse{}
	mi := &file_rpc_vda_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateCallResponse) ProtoMessage() {}

func (x *InitiateCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_vda_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateCallResponse.ProtoReflect.Descriptor instead.
func (*InitiateCallResponse) Descriptor() ([]byte, []int) {
	return file_rpc_vda_proto_rawDescGZIP(), []int{2}
}

func (x *InitiateCallResponse) GetCallID() string {
	if x != nil {
		return x.CallID
	}
	return ""
}

func (x *InitiateCallResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *InitiateCallResponse) GetLiveKitRoom() string {
	if x != nil {
		return x.LiveKitRoom
	}
	return ""
}

func (x *InitiateCallResponse) GetLiveKitToken() string {
	if x != nil {
		return x.LiveKitToken
	}
	return ""
}

type AcceptCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallID        string                 `protobuf:"bytes,1,opt,name=CallID,proto3" json:"CallID,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptCallRequest) Reset() {
	*x = AcceptCallRequest{}
	mi := &file_rpc_vda_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptCallRequest) ProtoMessage() {}

func (x *AcceptCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_vda_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptCallRequest.ProtoReflect.Descriptor instead.
func (*AcceptCallRequest) Descriptor() ([]byte, []int) {
	return file_rpc_vda_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptCallRequest) GetCallID() string {
	if x != nil {
		return x.CallID
	}
	return ""
}

func (x *AcceptCallRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type AcceptCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallID        string                 `protobuf:"bytes,1,opt,name=CallID,proto3" json:"CallID,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=State,proto3" json:"State,omitempty"`
	LiveKitToken  string                 `protobuf:"bytes,3,opt,name=LiveKitToken,proto3" json:"LiveKitToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptCallResponse) Reset() {
	*x = AcceptCallResponse{}
	mi := &file_rpc_vda_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptCallResponse) ProtoMessage() {}

func (x *AcceptCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_vda_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptCallResponse.ProtoReflect.Descriptor instead.
func (*AcceptCallResponse) Descriptor() ([]byte, []int) {
	return file_rpc_vda_proto_rawDescGZIP(), []int{4}
}

func (x *AcceptCallResponse) GetCallID() string {
	if x != nil {
		return x.CallID
	}
	return ""
}

func (x *AcceptCallResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AcceptCallResponse) GetLiveKitToken() string {
	if x != nil {
		return x.LiveKitToken
	}
	return ""
}

type RejectCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallID        string                 `protobuf:"bytes,1,opt,name=CallID,proto3" json:"CallID,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectCallRequest) Reset() {
	*x = RejectCallRequest{}
	mi := &file_rpc_vda_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectCallRequest) ProtoMessage() {}

func (x *RejectCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_vda_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectCallRequest.ProtoReflect.Descriptor instead.
func (*RejectCallRequest) Descriptor() ([]byte, []int) {
	return file_rpc_vda_proto_rawDescGZIP(), []int{5}
}

func (x *RejectCallRequest) GetCallID() string {
	if x != nil {
		return x.CallID
	}
	return ""
}

func (x *RejectCallRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type EndCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallID        string                 `protobuf:"bytes,1,opt,name=CallID,proto3" json:"CallID,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndCallRequest) Reset() {
	*x = EndCallRequest{}
	mi := &file_rpc_vda_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndCallRequest) ProtoMessage() {}

func (x *EndCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_vda_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndCallRequest.ProtoReflect.Descriptor instead.
func (*EndCallRequest) Descriptor() ([]byte, []int) {
	return file_rpc_vda_proto_rawDescGZIP(), []int{6}
}

func (x *EndCallRequest) GetCallID() string {
	if x != nil {
		return x.CallID
	}
	return ""
}

func (x *EndCallRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type CancelCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallID        string                 `protobuf:"bytes,1,opt,name=CallID,proto3" json:"CallID,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelCallRequest) Reset() {
	*x = CancelCallRequest{}
	mi := &file_rpc_vda_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelCallRequest) ProtoMessage() {}

func (x *CancelCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_vda_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelCallRequest.ProtoReflect.Descriptor instead.
func (*CancelCallRequest) Descriptor() ([]byte, []int) {
	return file_rpc_vda_proto_rawDescGZIP(), []int{7}
}

func (x *CancelCallRequest) GetCallID() string {
	if x != nil {
		return x.CallID
	}
	return ""
}

func (x *CancelCallRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type JoinVoiceRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomID        string                 `protobuf:"bytes,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	User          *CallerInfo            `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinVoiceRoomRequest) Reset() {
	*x = JoinVoiceRoomRequest{}
	mi := &file_rpc_vda_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinVoiceRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinVoiceRoomRequest) ProtoMessage() {}

func (x *JoinVoiceRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_vda_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinVoiceRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinVoiceRoomRequest) Descriptor() ([]byte, []int) {
	return file_rpc_vda_proto_rawDescGZIP(), []int{8}
}

func (x *JoinVoiceRoomRequest) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

func (x *JoinVoiceRoomRequest) GetUser() *CallerInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type JoinVoiceRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomID        string                 `protobuf:"bytes,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	LiveKitToken  string                 `protobuf:"bytes,2,opt,name=LiveKitToken,proto3" json:"LiveKitToken,omitempty"`
	Participants  []int64                `protobuf:"varint,3,rep,packed,name=Participants,proto3" json:"Participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinVoiceRoomResponse) Reset() {
	*x = JoinVoiceRoomResponse{}
	mi := &file_rpc_vda_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinVoiceRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinVoiceRoomResponse) ProtoMessage() {}

func (x *JoinVoiceRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_vda_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinVoiceRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinVoiceRoomResponse) Descriptor() ([]byte, []int) {
	return file_rpc_vda_proto_rawDescGZIP(), []int{9}
}

func (x *JoinVoiceRoomResponse) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

func (x *JoinVoiceRoomResponse) GetLiveKitToken() string {
	if x != nil {
		return x.LiveKitToken
	}
	return ""
}

func (x *JoinVoiceRoomResponse) GetParticipants() []int64 {
	if x != nil {
		return x.Participants
	}
	return nil
}

type LeaveVoiceRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomID        string                 `protobuf:"bytes,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveVoiceRoomRequest) Reset() {
	*x = LeaveVoiceRoomRequest{}
	mi := &file_rpc_vda_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveVoiceRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveVoiceRoomRequest) ProtoMessage() {}

func (x *LeaveVoiceRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_vda_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveVoiceRoomRequest.ProtoReflect.Descriptor instead.
func (*LeaveVoiceRoomRequest) Descriptor() ([]byte, []int) {
	return file_rpc_vda_proto_rawDescGZIP(), []int{10}
}

func (x *LeaveVoiceRoomRequest) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

func (x *LeaveVoiceRoomRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type MuteToggleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomID        string                 `protobuf:"bytes,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Muted         bool                   `protobuf:"varint,3,opt,name=Muted,proto3" json:"Muted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuteToggleRequest) Reset() {
	*x = MuteToggleRequest{}
	mi := &file_rpc_vda_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuteToggleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuteToggleRequest) ProtoMessage() {}

func (x *MuteToggleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_vda_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuteToggleRequest.ProtoReflect.Descriptor instead.
func (*MuteToggleRequest) Descriptor() ([]byte, []int) {
	return file_rpc_vda_proto_rawDescGZIP(), []int{11}
}

func (x *MuteToggleRequest) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

func (x *MuteToggleRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *MuteToggleRequest) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

type MuteToggleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomID        string                 `protobuf:"bytes,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Muted         bool                   `protobuf:"varint,3,opt,name=Muted,proto3" json:"Muted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuteToggleResponse) Reset() {
	*x = MuteToggleResponse{}
	mi := &file_rpc_vda_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuteToggleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuteToggleResponse) ProtoMessage() {}

func (x *MuteToggleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_vda_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuteToggleResponse.ProtoReflect.Descriptor instead.
func (*MuteToggleResponse) Descriptor() ([]byte, []int) {
	return file_rpc_vda_proto_rawDescGZIP(), []int{12}
}

func (x *MuteToggleResponse) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

func (x *MuteToggleResponse) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *MuteToggleResponse) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

type VoiceEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=Action,proto3" json:"Action,omitempty"`
	Caller        *CallerInfo            `protobuf:"bytes,2,opt,name=Caller,proto3" json:"Caller,omitempty"`
	CallID        string                 `protobuf:"bytes,3,opt,name=CallID,proto3" json:"CallID,omitempty"`
	RoomID        string                 `protobuf:"bytes,4,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	ReceiverID    int64                  `protobuf:"varint,5,opt,name=ReceiverID,proto3" json:"ReceiverID,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,6,opt,name=PayloadJson,proto3" json:"PayloadJson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceEventRequest) Reset() {
	*x = VoiceEventRequest{}
	mi := &file_rpc_vda_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceEventRequest) ProtoMessage() {}

func (x *VoiceEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_vda_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceEventRequest.ProtoReflect.Descriptor instead.
func (*VoiceEventRequest) Descriptor() ([]byte, []int) {
	return file_rpc_vda_proto_rawDescGZIP(), []int{13}
}

func (x *VoiceEventRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *VoiceEventRequest) GetCaller() *CallerInfo {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *VoiceEventRequest) GetCallID() string {
	if x != nil {
		return x.CallID
	}
	return ""
}

func (x *VoiceEventRequest) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

func (x *VoiceEventRequest) GetReceiverID() int64 {
	if x != nil {
		return x.ReceiverID
	}
	return 0
}

func (x *VoiceEventRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type VoiceEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallID        string                 `protobuf:"bytes,1,opt,name=CallID,proto3" json:"CallID,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=State,proto3" json:"State,omitempty"`
	LiveKitToken  string                 `protobuf:"bytes,3,opt,name=LiveKitToken,proto3" json:"LiveKitToken,omitempty"`
	LiveKitRoom   string                 `protobuf:"bytes,4,opt,name=LiveKitRoom,proto3" json:"LiveKitRoom,omitempty"`
	PushJson      string                 `protobuf:"bytes,5,opt,name=PushJson,proto3" json:"PushJson,omitempty"`
	PushTargets   []int64                `protobuf:"varint,6,rep,packed,name=PushTargets,proto3" json:"PushTargets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceEventResponse) Reset() {
	*x = VoiceEventResponse{}
	mi := &file_rpc_vda_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceEventResponse) ProtoMessage() {}

func (x *VoiceEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_vda_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceEventResponse.ProtoReflect.Descriptor instead.
func (*VoiceEventResponse) Descriptor() ([]byte, []int) {
	return file_rpc_vda_proto_rawDescGZIP(), []int{14}
}

func (x *VoiceEventResponse) GetCallID() string {
	if x != nil {
		return x.CallID
	}
	return ""
}

func (x *VoiceEventResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *VoiceEventResponse) GetLiveKitToken() string {
	if x != nil {
		return x.LiveKitToken
	}
	return ""
}

func (x *VoiceEventResponse) GetLiveKitRoom() string {
	if x != nil {
		return x.LiveKitRoom
	}
	return ""
}

func (x *VoiceEventResponse) GetPushJson() string {
	if x != nil {
		return x.PushJson
	}
	return ""
}

func (x *VoiceEventResponse) GetPushTargets() []int64 {
	if x != nil {
		return x.PushTargets
	}
	return nil
}

type GetCallStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallID        string                 `protobuf:"bytes,1,opt,name=CallID,proto3" json:"CallID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallStateRequest) Reset() {
	*x = GetCallStateRequest{}
	mi := &file_rpc_vda_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallStateRequest) ProtoMessage() {}

func (x *GetCallStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_vda_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallStateRequest.ProtoReflect.Descriptor instead.
func (*GetCallStateRequest) Descriptor() ([]byte, []int) {
	return file_rpc_vda_proto_rawDescGZIP(), []int{15}
}

func (x *GetCallStateRequest) GetCallID() string {
	if x != nil {
		return x.CallID
	}
	return ""
}

type CallStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallID        string                 `protobuf:"bytes,1,opt,name=CallID,proto3" json:"CallID,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=State,proto3" json:"State,omitempty"`
	Caller        int64                  `protobuf:"varint,3,opt,name=Caller,proto3" json:"Caller,omitempty"`
	Callee        int64                  `protobuf:"varint,4,opt,name=Callee,proto3" json:"Callee,omitempty"`
	LiveKitRoom   string                 `protobuf:"bytes,5,opt,name=LiveKitRoom,proto3" json:"LiveKitRoom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallStateResponse) Reset() {
	*x = CallStateResponse{}
	mi := &file_rpc_vda_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallStateResponse) ProtoMessage() {}

func (x *CallStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_vda_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallStateResponse.ProtoReflect.Descriptor instead.
func (*CallStateResponse) Descriptor() ([]byte, []int) {
	return file_rpc_vda_proto_rawDescGZIP(), []int{16}
}

func (x *CallStateResponse) GetCallID() string {
	if x != nil {
		return x.CallID
	}
	return ""
}

func (x *CallStateResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CallStateResponse) GetCaller() int64 {
	if x != nil {
		return x.Caller
	}
	return 0
}

func (x *CallStateResponse) GetCallee() int64 {
	if x != nil {
		return x.Callee
	}
	return 0
}

func (x *CallStateResponse) GetLiveKitRoom() string {
	if x != nil {
		return x.LiveKitRoom
	}
	return ""
}

type GetRoomStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomID        string                 `protobuf:"bytes,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomStateRequest) Reset() {
	*x = GetRoomStateRequest{}
	mi := &file_rpc_vda_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomStateRequest) ProtoMessage() {}

func (x *GetRoomStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_vda_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomStateRequest.ProtoReflect.Descriptor instead.
func (*GetRoomStateRequest) Descriptor() ([]byte, []int) {
	return file_rpc_vda_proto_rawDescGZIP(), []int{17}
}

func (x *GetRoomStateRequest) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

type RoomStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomID        string                 `protobuf:"bytes,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	Participants  []int64                `protobuf:"varint,2,rep,packed,name=Participants,proto3" json:"Participants,omitempty"`
	Muted         []int64                `protobuf:"varint,3,rep,packed,name=Muted,proto3" json:"Muted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomStateResponse) Reset() {
	*x = RoomStateResponse{}
	mi := &file_rpc_vda_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomStateResponse) ProtoMessage() {}

func (x *RoomStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_vda_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomStateResponse.ProtoReflect.Descriptor instead.
func (*RoomStateResponse) Descriptor() ([]byte, []int) {
	return file_rpc_vda_proto_rawDescGZIP(), []int{18}
}

func (x *RoomStateResponse) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

func (x *RoomStateResponse) GetParticipants() []int64 {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *RoomStateResponse) GetMuted() []int64 {
	if x != nil {
		return x.Muted
	}
	return nil
}

type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_rpc_vda_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_vda_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_rpc_vda_proto_rawDescGZIP(), []int{19}
}

func (x *ActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rpc_vda_proto protoreflect.FileDescriptor

const file_rpc_vda_proto_rawDesc = "" +
	"\n" +
	"\rrpc/vda.proto\x12\tvdaclient\"\x98\x01\n" +
	"\n" +
	"CallerInfo\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x03R\x06UserID\x12\x16\n" +
	"\x06Domain\x18\x02 \x01(\tR\x06Domain\x12\x1a\n" +
	"\bTenantID\x18\x03 \x01(\tR\bTenantID\x12\x1c\n" +
	"\tProjectID\x18\x04 \x01(\tR\tProjectID\x12 \n" +
	"\vEnvironment\x18\x05 \x01(\tR\vEnvironment\"\\\n" +
	"\x13InitiateCallRequest\x12-\n" +
	"\x06Caller\x18\x01 \x01(\v2\x15.vdaclient.CallerInfoR\x06Caller\x12\x16\n" +
	"\x06Callee\x18\x02 \x01(\x03R\x06Callee\"\x8a\x01\n" +
	"\x14InitiateCallResponse\x12\x16\n" +
	"\x06CallID\x18\x01 \x01(\tR\x06CallID\x12\x14\n" +
	"\x05State\x18\x02 \x01(\tR\x05State\x12 \n" +
	"\vLiveKitRoom\x18\x03 \x01(\tR\vLiveKitRoom\x12\"\n" +
	"\fLiveKitToken\x18\x04 \x01(\tR\fLiveKitToken\"C\n" +
	"\x11AcceptCallRequest\x12\x16\n" +
	"\x06CallID\x18\x01 \x01(\tR\x06CallID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\x03R\x06UserID\"f\n" +
	"\x12AcceptCallResponse\x12\x16\n" +
	"\x06CallID\x18\x01 \x01(\tR\x06CallID\x12\x14\n" +
	"\x05State\x18\x02 \x01(\tR\x05State\x12\"\n" +
	"\fLiveKitToken\x18\x03 \x01(\tR\fLiveKitToken\"C\n" +
	"\x11RejectCallRequest\x12\x16\n" +
	"\x06CallID\x18\x01 \x01(\tR\x06CallID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\x03R\x06UserID\"@\n" +
	"\x0eEndCallRequest\x12\x16\n" +
	"\x06CallID\x18\x01 \x01(\tR\x06CallID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\x03R\x06UserID\"C\n" +
	"\x11CancelCallRequest\x12\x16\n" +
	"\x06CallID\x18\x01 \x01(\tR\x06CallID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\x03R\x06UserID\"Y\n" +
	"\x14JoinVoiceRoomRequest\x12\x16\n" +
	"\x06RoomID\x18\x01 \x01(\tR\x06RoomID\x12)\n" +
	"\x04User\x18\x02 \x01(\v2\x15.vdaclient.CallerInfoR\x04User\"w\n" +
	"\x15JoinVoiceRoomResponse\x12\x16\n" +
	"\x06RoomID\x18\x01 \x01(\tR\x06RoomID\x12\"\n" +
	"\fLiveKitToken\x18\x02 \x01(\tR\fLiveKitToken\x12\"\n" +
	"\fParticipants\x18\x03 \x03(\x03R\fParticipants\"G\n" +
	"\x15LeaveVoiceRoomRequest\x12\x16\n" +
	"\x06RoomID\x18\x01 \x01(\tR\x06RoomID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\x03R\x06UserID\"Y\n" +
	"\x11MuteToggleRequest\x12\x16\n" +
	"\x06RoomID\x18\x01 \x01(\tR\x06RoomID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\x03R\x06UserID\x12\x14\n" +
	"\x05Muted\x18\x03 \x01(\bR\x05Muted\"Z\n" +
	"\x12MuteToggleResponse\x12\x16\n" +
	"\x06RoomID\x18\x01 \x01(\tR\x06RoomID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\x03R\x06UserID\x12\x14\n" +
	"\x05Muted\x18\x03 \x01(\bR\x05Muted\"\xcc\x01\n" +
	"\x11VoiceEventRequest\x12\x16\n" +
	"\x06Action\x18\x01 \x01(\tR\x06Action\x12-\n" +
	"\x06Caller\x18\x02 \x01(\v2\x15.vdaclient.CallerInfoR\x06Caller\x12\x16\n" +
	"\x06CallID\x18\x03 \x01(\tR\x06CallID\x12\x16\n" +
	"\x06RoomID\x18\x04 \x01(\tR\x06RoomID\x12\x1e\n" +
	"\n" +
	"ReceiverID\x18\x05 \x01(\x03R\n" +
	"ReceiverID\x12 \n" +
	"\vPayloadJson\x18\x06 \x01(\tR\vPayloadJson\"\xc6\x01\n" +
	"\x12VoiceEventResponse\x12\x16\n" +
	"\x06CallID\x18\x01 \x01(\tR\x06CallID\x12\x14\n" +
	"\x05State\x18\x02 \x01(\tR\x05State\x12\"\n" +
	"\fLiveKitToken\x18\x03 \x01(\tR\fLiveKitToken\x12 \n" +
	"\vLiveKitRoom\x18\x04 \x01(\tR\vLiveKitRoom\x12\x1a\n" +
	"\bPushJson\x18\x05 \x01(\tR\bPushJson\x12 \n" +
	"\vPushTargets\x18\x06 \x03(\x03R\vPushTargets\"-\n" +
	"\x13GetCallStateRequest\x12\x16\n" +
	"\x06CallID\x18\x01 \x01(\tR\x06CallID\"\x93\x01\n" +
	"\x11CallStateResponse\x12\x16\n" +
	"\x06CallID\x18\x01 \x01(\tR\x06CallID\x12\x14\n" +
	"\x05State\x18\x02 \x01(\tR\x05State\x12\x16\n" +
	"\x06Caller\x18\x03 \x01(\x03R\x06Caller\x12\x16\n" +
	"\x06Callee\x18\x04 \x01(\x03R\x06Callee\x12 \n" +
	"\vLiveKitRoom\x18\x05 \x01(\tR\vLiveKitRoom\"-\n" +
	"\x13GetRoomStateRequest\x12\x16\n" +
	"\x06RoomID\x18\x01 \x01(\tR\x06RoomID\"e\n" +
	"\x11RoomStateResponse\x12\x16\n" +
	"\x06RoomID\x18\x01 \x01(\tR\x06RoomID\x12\"\n" +
	"\fParticipants\x18\x02 \x03(\x03R\fParticipants\x12\x14\n" +
	"\x05Muted\x18\x03 \x03(\x03R\x05Muted\"D\n" +
	"\x0eActionResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage2\xcb\x06\n" +
	"\x03VDA\x12O\n" +
	"\fInitiateCall\x12\x1e.vdaclient.InitiateCallRequest\x1a\x1f.vdaclient.InitiateCallResponse\x12I\n" +
	"\n" +
	"AcceptCall\x12\x1c.vdaclient.AcceptCallRequest\x1a\x1d.vdaclient.AcceptCallResponse\x12E\n" +
	"\n" +
	"RejectCall\x12\x1c.vdaclient.RejectCallRequest\x1a\x19.vdaclient.ActionResponse\x12?\n" +
	"\aEndCall\x12\x19.vdaclient.EndCallRequest\x1a\x19.vdaclient.ActionResponse\x12E\n" +
	"\n" +
	"CancelCall\x12\x1c.vdaclient.CancelCallRequest\x1a\x19.vdaclient.ActionResponse\x12R\n" +
	"\rJoinVoiceRoom\x12\x1f.vdaclient.JoinVoiceRoomRequest\x1a .vdaclient.JoinVoiceRoomResponse\x12M\n" +
	"\x0eLeaveVoiceRoom\x12 .vdaclient.LeaveVoiceRoomRequest\x1a\x19.vdaclient.ActionResponse\x12I\n" +
	"\n" +
	"MuteToggle\x12\x1c.vdaclient.MuteToggleRequest\x1a\x1d.vdaclient.MuteToggleResponse\x12O\n" +
	"\x10HandleVoiceEvent\x12\x1c.vdaclient.VoiceEventRequest\x1a\x1d.vdaclient.VoiceEventResponse\x12L\n" +
	"\fGetCallState\x12\x1e.vdaclient.GetCallStateRequest\x1a\x1c.vdaclient.CallStateResponse\x12L\n" +
	"\fGetRoomState\x12\x1e.vdaclient.GetRoomStateRequest\x1a\x1c.vdaclient.RoomStateResponseB\x06Z\x04/vdab\x06proto3"

var (
	file_rpc_vda_proto_rawDescOnce sync.Once
	file_rpc_vda_proto_rawDescData []byte
)

func file_rpc_vda_proto_rawDescGZIP() []byte {
	file_rpc_vda_proto_rawDescOnce.Do(func() {
		file_rpc_vda_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_vda_proto_rawDesc), len(file_rpc_vda_proto_rawDesc)))
	})
	return file_rpc_vda_proto_rawDescData
}

var file_rpc_vda_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_rpc_vda_proto_goTypes = []any{
	(*CallerInfo)(nil),            // 0: vdaclient.CallerInfo
	(*InitiateCallRequest)(nil),   // 1: vdaclient.InitiateCallRequest
	(*InitiateCallResponse)(nil),  // 2: vdaclient.InitiateCallResponse
	(*AcceptCallRequest)(nil),     // 3: vdaclient.AcceptCallRequest
	(*AcceptCallResponse)(nil),    // 4: vdaclient.AcceptCallResponse
	(*RejectCallRequest)(nil),     // 5: vdaclient.RejectCallRequest
	(*EndCallRequest)(nil),        // 6: vdaclient.EndCallRequest
	(*CancelCallRequest)(nil),     // 7: vdaclient.CancelCallRequest
	(*JoinVoiceRoomRequest)(nil),  // 8: vdaclient.JoinVoiceRoomRequest
	(*JoinVoiceRoomResponse)(nil), // 9: vdaclient.JoinVoiceRoomResponse
	(*LeaveVoiceRoomRequest)(nil), // 10: vdaclient.LeaveVoiceRoomRequest
	(*MuteToggleRequest)(nil),     // 11: vdaclient.MuteToggleRequest
	(*MuteToggleResponse)(nil),    // 12: vdaclient.MuteToggleResponse
	(*VoiceEventRequest)(nil),     // 13: vdaclient.VoiceEventRequest
	(*VoiceEventResponse)(nil),    // 14: vdaclient.VoiceEventResponse
	(*GetCallStateRequest)(nil),   // 15: vdaclient.GetCallStateRequest
	(*CallStateResponse)(nil),     // 16: vdaclient.CallStateResponse
	(*GetRoomStateRequest)(nil),   // 17: vdaclient.GetRoomStateRequest
	(*RoomStateResponse)(nil),     // 18: vdaclient.RoomStateResponse
	(*ActionResponse)(nil),        // 19: vdaclient.ActionResponse
}
var file_rpc_vda_proto_depIdxs = []int32{
	0,  // 0: vdaclient.InitiateCallRequest.Caller:type_name -> vdaclient.CallerInfo
	0,  // 1: vdaclient.JoinVoiceRoomRequest.User:type_name -> vdaclient.CallerInfo
	0,  // 2: vdaclient.VoiceEventRequest.Caller:type_name -> vdaclient.CallerInfo
	1,  // 3: vdaclient.VDA.InitiateCall:input_type -> vdaclient.InitiateCallRequest
	3,  // 4: vdaclient.VDA.AcceptCall:input_type -> vdaclient.AcceptCallRequest
	5,  // 5: vdaclient.VDA.RejectCall:input_type -> vdaclient.RejectCallRequest
	6,  // 6: vdaclient.VDA.EndCall:input_type -> vdaclient.EndCallRequest
	7,  // 7: vdaclient.VDA.CancelCall:input_type -> vdaclient.CancelCallRequest
	8,  // 8: vdaclient.VDA.JoinVoiceRoom:input_type -> vdaclient.JoinVoiceRoomRequest
	10, // 9: vdaclient.VDA.LeaveVoiceRoom:input_type -> vdaclient.LeaveVoiceRoomRequest
	11, // 10: vdaclient.VDA.MuteToggle:input_type -> vdaclient.MuteToggleRequest
	13, // 11: vdaclient.VDA.HandleVoiceEvent:input_type -> vdaclient.VoiceEventRequest
	15, // 12: vdaclient.VDA.GetCallState:input_type -> vdaclient.GetCallStateRequest
	17, // 13: vdaclient.VDA.GetRoomState:input_type -> vdaclient.GetRoomStateRequest
	2,  // 14: vdaclient.VDA.InitiateCall:output_type -> vdaclient.InitiateCallResponse
	4,  // 15: vdaclient.VDA.AcceptCall:output_type -> vdaclient.AcceptCallResponse
	19, // 16: vdaclient.VDA.RejectCall:output_type -> vdaclient.ActionResponse
	19, // 17: vdaclient.VDA.EndCall:output_type -> vdaclient.ActionResponse
	19, // 18: vdaclient.VDA.CancelCall:output_type -> vdaclient.ActionResponse
	9,  // 19: vdaclient.VDA.JoinVoiceRoom:output_type -> vdaclient.JoinVoiceRoomResponse
	19, // 20: vdaclient.VDA.LeaveVoiceRoom:output_type -> vdaclient.ActionResponse
	12, // 21: vdaclient.VDA.MuteToggle:output_type -> vdaclient.MuteToggleResponse
	14, // 22: vdaclient.VDA.HandleVoiceEvent:output_type -> vdaclient.VoiceEventResponse
	16, // 23: vdaclient.VDA.GetCallState:output_type -> vdaclient.CallStateResponse
	18, // 24: vdaclient.VDA.GetRoomState:output_type -> vdaclient.RoomStateResponse
	14, // [14:25] is the sub-list for method output_type
	3,  // [3:14] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_vda_proto_init() }
func file_rpc_vda_proto_init() {
	if File_rpc_vda_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_vda_proto_rawDesc), len(file_rpc_vda_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_vda_proto_goTypes,
		DependencyIndexes: file_rpc_vda_proto_depIdxs,
		MessageInfos:      file_rpc_vda_proto_msgTypes,
	}.Build()
	File_rpc_vda_proto = out.File
	file_rpc_vda_proto_goTypes = nil
	file_rpc_vda_proto_depIdxs = nil
}
