// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.4

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	deviceShadowFieldNames          = builder.RawFieldNames(&DeviceShadow{})
	deviceShadowRows                = strings.Join(deviceShadowFieldNames, ",")
	deviceShadowRowsExpectAutoSet   = strings.Join(stringx.Remove(deviceShadowFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	deviceShadowRowsWithPlaceHolder = strings.Join(stringx.Remove(deviceShadowFieldNames, "`device_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	deviceShadowModel interface {
		Insert(ctx context.Context, data *DeviceShadow) (sql.Result, error)
		FindOne(ctx context.Context, deviceId int64) (*DeviceShadow, error)
		Update(ctx context.Context, data *DeviceShadow) error
		Delete(ctx context.Context, deviceId int64) error
	}

	defaultDeviceShadowModel struct {
		conn  sqlx.SqlConn
		table string
	}

	DeviceShadow struct {
		DeviceId      int64          `db:"device_id"`
		DeviceName    string         `db:"device_name"`
		DesiredState  sql.NullString `db:"desired_state"`
		ReportedState sql.NullString `db:"reported_state"`
		DeltaState    sql.NullString `db:"delta_state"`
		Version       int64          `db:"version"`
		CreatedAt     int64          `db:"created_at"`
		UpdatedAt     int64          `db:"updated_at"`
	}
)

func newDeviceShadowModel(conn sqlx.SqlConn) *defaultDeviceShadowModel {
	return &defaultDeviceShadowModel{
		conn:  conn,
		table: "`device_shadow`",
	}
}

func (m *defaultDeviceShadowModel) Delete(ctx context.Context, deviceId int64) error {
	query := fmt.Sprintf("delete from %s where `device_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, deviceId)
	return err
}

func (m *defaultDeviceShadowModel) FindOne(ctx context.Context, deviceId int64) (*DeviceShadow, error) {
	query := fmt.Sprintf("select %s from %s where `device_id` = ? limit 1", deviceShadowRows, m.table)
	var resp DeviceShadow
	err := m.conn.QueryRowCtx(ctx, &resp, query, deviceId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDeviceShadowModel) Insert(ctx context.Context, data *DeviceShadow) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, deviceShadowRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DeviceId, data.DeviceName, data.DesiredState, data.ReportedState, data.DeltaState, data.Version)
	return ret, err
}

func (m *defaultDeviceShadowModel) Update(ctx context.Context, data *DeviceShadow) error {
	query := fmt.Sprintf("update %s set %s where `device_id` = ?", m.table, deviceShadowRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.DeviceName, data.DesiredState, data.ReportedState, data.DeltaState, data.Version, data.DeviceId)
	return err
}

func (m *defaultDeviceShadowModel) tableName() string {
	return m.table
}
