// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	platformProjectFieldNames          = builder.RawFieldNames(&PlatformProject{})
	platformProjectRows                = strings.Join(platformProjectFieldNames, ",")
	platformProjectRowsExpectAutoSet   = strings.Join(stringx.Remove(platformProjectFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	platformProjectRowsWithPlaceHolder = strings.Join(stringx.Remove(platformProjectFieldNames, "`project_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cachePlatformProjectProjectIdPrefix          = "cache:platformProject:projectId:"
	cachePlatformProjectTenantIdProjectKeyPrefix = "cache:platformProject:tenantId:projectKey:"
)

type (
	platformProjectModel interface {
		Insert(ctx context.Context, data *PlatformProject) (sql.Result, error)
		FindOne(ctx context.Context, projectId string) (*PlatformProject, error)
		FindOneByTenantIdProjectKey(ctx context.Context, tenantId string, projectKey string) (*PlatformProject, error)
		Update(ctx context.Context, data *PlatformProject) error
		Delete(ctx context.Context, projectId string) error
	}

	defaultPlatformProjectModel struct {
		sqlc.CachedConn
		table string
	}

	PlatformProject struct {
		ProjectId  string    `db:"project_id"`
		TenantId   string    `db:"tenant_id"`
		Name       string    `db:"name"`
		ProjectKey string    `db:"project_key"`
		Status     string    `db:"status"`
		CreatedAt  time.Time `db:"created_at"`
		UpdatedAt  time.Time `db:"updated_at"`
	}
)

func newPlatformProjectModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPlatformProjectModel {
	return &defaultPlatformProjectModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`platform_project`",
	}
}

func (m *defaultPlatformProjectModel) Delete(ctx context.Context, projectId string) error {
	data, err := m.FindOne(ctx, projectId)
	if err != nil {
		return err
	}

	platformProjectProjectIdKey := fmt.Sprintf("%s%v", cachePlatformProjectProjectIdPrefix, projectId)
	platformProjectTenantIdProjectKeyKey := fmt.Sprintf("%s%v:%v", cachePlatformProjectTenantIdProjectKeyPrefix, data.TenantId, data.ProjectKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `project_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, projectId)
	}, platformProjectProjectIdKey, platformProjectTenantIdProjectKeyKey)
	return err
}

func (m *defaultPlatformProjectModel) FindOne(ctx context.Context, projectId string) (*PlatformProject, error) {
	platformProjectProjectIdKey := fmt.Sprintf("%s%v", cachePlatformProjectProjectIdPrefix, projectId)
	var resp PlatformProject
	err := m.QueryRowCtx(ctx, &resp, platformProjectProjectIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `project_id` = ? limit 1", platformProjectRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, projectId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPlatformProjectModel) FindOneByTenantIdProjectKey(ctx context.Context, tenantId string, projectKey string) (*PlatformProject, error) {
	platformProjectTenantIdProjectKeyKey := fmt.Sprintf("%s%v:%v", cachePlatformProjectTenantIdProjectKeyPrefix, tenantId, projectKey)
	var resp PlatformProject
	err := m.QueryRowIndexCtx(ctx, &resp, platformProjectTenantIdProjectKeyKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `project_key` = ? limit 1", platformProjectRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, projectKey); err != nil {
			return nil, err
		}
		return resp.ProjectId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPlatformProjectModel) Insert(ctx context.Context, data *PlatformProject) (sql.Result, error) {
	platformProjectProjectIdKey := fmt.Sprintf("%s%v", cachePlatformProjectProjectIdPrefix, data.ProjectId)
	platformProjectTenantIdProjectKeyKey := fmt.Sprintf("%s%v:%v", cachePlatformProjectTenantIdProjectKeyPrefix, data.TenantId, data.ProjectKey)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, platformProjectRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ProjectId, data.TenantId, data.Name, data.ProjectKey, data.Status)
	}, platformProjectProjectIdKey, platformProjectTenantIdProjectKeyKey)
	return ret, err
}

func (m *defaultPlatformProjectModel) Update(ctx context.Context, newData *PlatformProject) error {
	data, err := m.FindOne(ctx, newData.ProjectId)
	if err != nil {
		return err
	}

	platformProjectProjectIdKey := fmt.Sprintf("%s%v", cachePlatformProjectProjectIdPrefix, data.ProjectId)
	platformProjectTenantIdProjectKeyKey := fmt.Sprintf("%s%v:%v", cachePlatformProjectTenantIdProjectKeyPrefix, data.TenantId, data.ProjectKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `project_id` = ?", m.table, platformProjectRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TenantId, newData.Name, newData.ProjectKey, newData.Status, newData.ProjectId)
	}, platformProjectProjectIdKey, platformProjectTenantIdProjectKeyKey)
	return err
}

func (m *defaultPlatformProjectModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePlatformProjectProjectIdPrefix, primary)
}

func (m *defaultPlatformProjectModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `project_id` = ? limit 1", platformProjectRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPlatformProjectModel) tableName() string {
	return m.table
}
