// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	platformTenantFieldNames          = builder.RawFieldNames(&PlatformTenant{})
	platformTenantRows                = strings.Join(platformTenantFieldNames, ",")
	platformTenantRowsExpectAutoSet   = strings.Join(stringx.Remove(platformTenantFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	platformTenantRowsWithPlaceHolder = strings.Join(stringx.Remove(platformTenantFieldNames, "`tenant_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cachePlatformTenantTenantIdPrefix = "cache:platformTenant:tenantId:"
	cachePlatformTenantSlugPrefix     = "cache:platformTenant:slug:"
)

type (
	platformTenantModel interface {
		Insert(ctx context.Context, data *PlatformTenant) (sql.Result, error)
		FindOne(ctx context.Context, tenantId string) (*PlatformTenant, error)
		FindOneBySlug(ctx context.Context, slug string) (*PlatformTenant, error)
		Update(ctx context.Context, data *PlatformTenant) error
		Delete(ctx context.Context, tenantId string) error
	}

	defaultPlatformTenantModel struct {
		sqlc.CachedConn
		table string
	}

	PlatformTenant struct {
		TenantId  string    `db:"tenant_id"`
		Name      string    `db:"name"`
		Slug      string    `db:"slug"`
		Status    string    `db:"status"`
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newPlatformTenantModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPlatformTenantModel {
	return &defaultPlatformTenantModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`platform_tenant`",
	}
}

func (m *defaultPlatformTenantModel) Delete(ctx context.Context, tenantId string) error {
	data, err := m.FindOne(ctx, tenantId)
	if err != nil {
		return err
	}

	platformTenantSlugKey := fmt.Sprintf("%s%v", cachePlatformTenantSlugPrefix, data.Slug)
	platformTenantTenantIdKey := fmt.Sprintf("%s%v", cachePlatformTenantTenantIdPrefix, tenantId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `tenant_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, tenantId)
	}, platformTenantSlugKey, platformTenantTenantIdKey)
	return err
}

func (m *defaultPlatformTenantModel) FindOne(ctx context.Context, tenantId string) (*PlatformTenant, error) {
	platformTenantTenantIdKey := fmt.Sprintf("%s%v", cachePlatformTenantTenantIdPrefix, tenantId)
	var resp PlatformTenant
	err := m.QueryRowCtx(ctx, &resp, platformTenantTenantIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? limit 1", platformTenantRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, tenantId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPlatformTenantModel) FindOneBySlug(ctx context.Context, slug string) (*PlatformTenant, error) {
	platformTenantSlugKey := fmt.Sprintf("%s%v", cachePlatformTenantSlugPrefix, slug)
	var resp PlatformTenant
	err := m.QueryRowIndexCtx(ctx, &resp, platformTenantSlugKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `slug` = ? limit 1", platformTenantRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, slug); err != nil {
			return nil, err
		}
		return resp.TenantId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPlatformTenantModel) Insert(ctx context.Context, data *PlatformTenant) (sql.Result, error) {
	platformTenantSlugKey := fmt.Sprintf("%s%v", cachePlatformTenantSlugPrefix, data.Slug)
	platformTenantTenantIdKey := fmt.Sprintf("%s%v", cachePlatformTenantTenantIdPrefix, data.TenantId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, platformTenantRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantId, data.Name, data.Slug, data.Status)
	}, platformTenantSlugKey, platformTenantTenantIdKey)
	return ret, err
}

func (m *defaultPlatformTenantModel) Update(ctx context.Context, newData *PlatformTenant) error {
	data, err := m.FindOne(ctx, newData.TenantId)
	if err != nil {
		return err
	}

	platformTenantSlugKey := fmt.Sprintf("%s%v", cachePlatformTenantSlugPrefix, data.Slug)
	platformTenantTenantIdKey := fmt.Sprintf("%s%v", cachePlatformTenantTenantIdPrefix, data.TenantId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `tenant_id` = ?", m.table, platformTenantRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.Slug, newData.Status, newData.TenantId)
	}, platformTenantSlugKey, platformTenantTenantIdKey)
	return err
}

func (m *defaultPlatformTenantModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePlatformTenantTenantIdPrefix, primary)
}

func (m *defaultPlatformTenantModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `tenant_id` = ? limit 1", platformTenantRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPlatformTenantModel) tableName() string {
	return m.table
}
