// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	platformEnvironmentFieldNames          = builder.RawFieldNames(&PlatformEnvironment{})
	platformEnvironmentRows                = strings.Join(platformEnvironmentFieldNames, ",")
	platformEnvironmentRowsExpectAutoSet   = strings.Join(stringx.Remove(platformEnvironmentFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	platformEnvironmentRowsWithPlaceHolder = strings.Join(stringx.Remove(platformEnvironmentFieldNames, "`environment_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cachePlatformEnvironmentEnvironmentIdPrefix = "cache:platformEnvironment:environmentId:"
	cachePlatformEnvironmentProjectIdNamePrefix = "cache:platformEnvironment:projectId:name:"
)

type (
	platformEnvironmentModel interface {
		Insert(ctx context.Context, data *PlatformEnvironment) (sql.Result, error)
		FindOne(ctx context.Context, environmentId string) (*PlatformEnvironment, error)
		FindOneByProjectIdName(ctx context.Context, projectId string, name string) (*PlatformEnvironment, error)
		Update(ctx context.Context, data *PlatformEnvironment) error
		Delete(ctx context.Context, environmentId string) error
	}

	defaultPlatformEnvironmentModel struct {
		sqlc.CachedConn
		table string
	}

	PlatformEnvironment struct {
		EnvironmentId string    `db:"environment_id"`
		ProjectId     string    `db:"project_id"`
		Name          string    `db:"name"`
		DisplayName   string    `db:"display_name"`
		Status        string    `db:"status"`
		CreatedAt     time.Time `db:"created_at"`
		UpdatedAt     time.Time `db:"updated_at"`
	}
)

func newPlatformEnvironmentModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPlatformEnvironmentModel {
	return &defaultPlatformEnvironmentModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`platform_environment`",
	}
}

func (m *defaultPlatformEnvironmentModel) Delete(ctx context.Context, environmentId string) error {
	data, err := m.FindOne(ctx, environmentId)
	if err != nil {
		return err
	}

	platformEnvironmentEnvironmentIdKey := fmt.Sprintf("%s%v", cachePlatformEnvironmentEnvironmentIdPrefix, environmentId)
	platformEnvironmentProjectIdNameKey := fmt.Sprintf("%s%v:%v", cachePlatformEnvironmentProjectIdNamePrefix, data.ProjectId, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `environment_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, environmentId)
	}, platformEnvironmentEnvironmentIdKey, platformEnvironmentProjectIdNameKey)
	return err
}

func (m *defaultPlatformEnvironmentModel) FindOne(ctx context.Context, environmentId string) (*PlatformEnvironment, error) {
	platformEnvironmentEnvironmentIdKey := fmt.Sprintf("%s%v", cachePlatformEnvironmentEnvironmentIdPrefix, environmentId)
	var resp PlatformEnvironment
	err := m.QueryRowCtx(ctx, &resp, platformEnvironmentEnvironmentIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `environment_id` = ? limit 1", platformEnvironmentRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, environmentId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPlatformEnvironmentModel) FindOneByProjectIdName(ctx context.Context, projectId string, name string) (*PlatformEnvironment, error) {
	platformEnvironmentProjectIdNameKey := fmt.Sprintf("%s%v:%v", cachePlatformEnvironmentProjectIdNamePrefix, projectId, name)
	var resp PlatformEnvironment
	err := m.QueryRowIndexCtx(ctx, &resp, platformEnvironmentProjectIdNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `project_id` = ? and `name` = ? limit 1", platformEnvironmentRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, projectId, name); err != nil {
			return nil, err
		}
		return resp.EnvironmentId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPlatformEnvironmentModel) Insert(ctx context.Context, data *PlatformEnvironment) (sql.Result, error) {
	platformEnvironmentEnvironmentIdKey := fmt.Sprintf("%s%v", cachePlatformEnvironmentEnvironmentIdPrefix, data.EnvironmentId)
	platformEnvironmentProjectIdNameKey := fmt.Sprintf("%s%v:%v", cachePlatformEnvironmentProjectIdNamePrefix, data.ProjectId, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, platformEnvironmentRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.EnvironmentId, data.ProjectId, data.Name, data.DisplayName, data.Status)
	}, platformEnvironmentEnvironmentIdKey, platformEnvironmentProjectIdNameKey)
	return ret, err
}

func (m *defaultPlatformEnvironmentModel) Update(ctx context.Context, newData *PlatformEnvironment) error {
	data, err := m.FindOne(ctx, newData.EnvironmentId)
	if err != nil {
		return err
	}

	platformEnvironmentEnvironmentIdKey := fmt.Sprintf("%s%v", cachePlatformEnvironmentEnvironmentIdPrefix, data.EnvironmentId)
	platformEnvironmentProjectIdNameKey := fmt.Sprintf("%s%v:%v", cachePlatformEnvironmentProjectIdNamePrefix, data.ProjectId, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `environment_id` = ?", m.table, platformEnvironmentRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ProjectId, newData.Name, newData.DisplayName, newData.Status, newData.EnvironmentId)
	}, platformEnvironmentEnvironmentIdKey, platformEnvironmentProjectIdNameKey)
	return err
}

func (m *defaultPlatformEnvironmentModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePlatformEnvironmentEnvironmentIdPrefix, primary)
}

func (m *defaultPlatformEnvironmentModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `environment_id` = ? limit 1", platformEnvironmentRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPlatformEnvironmentModel) tableName() string {
	return m.table
}
