// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	platformTenantMemberFieldNames          = builder.RawFieldNames(&PlatformTenantMember{})
	platformTenantMemberRows                = strings.Join(platformTenantMemberFieldNames, ",")
	platformTenantMemberRowsExpectAutoSet   = strings.Join(stringx.Remove(platformTenantMemberFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	platformTenantMemberRowsWithPlaceHolder = strings.Join(stringx.Remove(platformTenantMemberFieldNames, "`tenant_member_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cachePlatformTenantMemberTenantMemberIdPrefix   = "cache:platformTenantMember:tenantMemberId:"
	cachePlatformTenantMemberTenantIdMemberIdPrefix = "cache:platformTenantMember:tenantId:memberId:"
)

type (
	platformTenantMemberModel interface {
		Insert(ctx context.Context, data *PlatformTenantMember) (sql.Result, error)
		FindOne(ctx context.Context, tenantMemberId string) (*PlatformTenantMember, error)
		FindOneByTenantIdMemberId(ctx context.Context, tenantId string, memberId string) (*PlatformTenantMember, error)
		Update(ctx context.Context, data *PlatformTenantMember) error
		Delete(ctx context.Context, tenantMemberId string) error
	}

	defaultPlatformTenantMemberModel struct {
		sqlc.CachedConn
		table string
	}

	PlatformTenantMember struct {
		TenantMemberId string    `db:"tenant_member_id"`
		TenantId       string    `db:"tenant_id"`
		MemberId       string    `db:"member_id"`
		Role           string    `db:"role"`
		Status         string    `db:"status"`
		JoinedAt       time.Time `db:"joined_at"`
		CreatedAt      time.Time `db:"created_at"`
		UpdatedAt      time.Time `db:"updated_at"`
	}
)

func newPlatformTenantMemberModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPlatformTenantMemberModel {
	return &defaultPlatformTenantMemberModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`platform_tenant_member`",
	}
}

func (m *defaultPlatformTenantMemberModel) Delete(ctx context.Context, tenantMemberId string) error {
	data, err := m.FindOne(ctx, tenantMemberId)
	if err != nil {
		return err
	}

	platformTenantMemberTenantIdMemberIdKey := fmt.Sprintf("%s%v:%v", cachePlatformTenantMemberTenantIdMemberIdPrefix, data.TenantId, data.MemberId)
	platformTenantMemberTenantMemberIdKey := fmt.Sprintf("%s%v", cachePlatformTenantMemberTenantMemberIdPrefix, tenantMemberId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `tenant_member_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, tenantMemberId)
	}, platformTenantMemberTenantIdMemberIdKey, platformTenantMemberTenantMemberIdKey)
	return err
}

func (m *defaultPlatformTenantMemberModel) FindOne(ctx context.Context, tenantMemberId string) (*PlatformTenantMember, error) {
	platformTenantMemberTenantMemberIdKey := fmt.Sprintf("%s%v", cachePlatformTenantMemberTenantMemberIdPrefix, tenantMemberId)
	var resp PlatformTenantMember
	err := m.QueryRowCtx(ctx, &resp, platformTenantMemberTenantMemberIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `tenant_member_id` = ? limit 1", platformTenantMemberRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, tenantMemberId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPlatformTenantMemberModel) FindOneByTenantIdMemberId(ctx context.Context, tenantId string, memberId string) (*PlatformTenantMember, error) {
	platformTenantMemberTenantIdMemberIdKey := fmt.Sprintf("%s%v:%v", cachePlatformTenantMemberTenantIdMemberIdPrefix, tenantId, memberId)
	var resp PlatformTenantMember
	err := m.QueryRowIndexCtx(ctx, &resp, platformTenantMemberTenantIdMemberIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `member_id` = ? limit 1", platformTenantMemberRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tenantId, memberId); err != nil {
			return nil, err
		}
		return resp.TenantMemberId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPlatformTenantMemberModel) Insert(ctx context.Context, data *PlatformTenantMember) (sql.Result, error) {
	platformTenantMemberTenantIdMemberIdKey := fmt.Sprintf("%s%v:%v", cachePlatformTenantMemberTenantIdMemberIdPrefix, data.TenantId, data.MemberId)
	platformTenantMemberTenantMemberIdKey := fmt.Sprintf("%s%v", cachePlatformTenantMemberTenantMemberIdPrefix, data.TenantMemberId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, platformTenantMemberRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TenantMemberId, data.TenantId, data.MemberId, data.Role, data.Status, data.JoinedAt)
	}, platformTenantMemberTenantIdMemberIdKey, platformTenantMemberTenantMemberIdKey)
	return ret, err
}

func (m *defaultPlatformTenantMemberModel) Update(ctx context.Context, newData *PlatformTenantMember) error {
	data, err := m.FindOne(ctx, newData.TenantMemberId)
	if err != nil {
		return err
	}

	platformTenantMemberTenantIdMemberIdKey := fmt.Sprintf("%s%v:%v", cachePlatformTenantMemberTenantIdMemberIdPrefix, data.TenantId, data.MemberId)
	platformTenantMemberTenantMemberIdKey := fmt.Sprintf("%s%v", cachePlatformTenantMemberTenantMemberIdPrefix, data.TenantMemberId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `tenant_member_id` = ?", m.table, platformTenantMemberRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TenantId, newData.MemberId, newData.Role, newData.Status, newData.JoinedAt, newData.TenantMemberId)
	}, platformTenantMemberTenantIdMemberIdKey, platformTenantMemberTenantMemberIdKey)
	return err
}

func (m *defaultPlatformTenantMemberModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePlatformTenantMemberTenantMemberIdPrefix, primary)
}

func (m *defaultPlatformTenantMemberModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `tenant_member_id` = ? limit 1", platformTenantMemberRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPlatformTenantMemberModel) tableName() string {
	return m.table
}
