// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0-alpha

package handler

import (
	"net/http"

	"user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/user/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/register",
				Handler: RegisterHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/user/userinfo",
					Handler: UserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/user/profile/update",
					Handler: UpdateProfileHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/user/password/change",
					Handler: ChangePasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/user/mobile/change",
					Handler: ChangeMobileHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/user/code/send/mobile",
					Handler: SendMobileCodeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/user/code/send/email",
					Handler: SendEmailCodeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/user/email/bind",
					Handler: BindEmailHandler(serverCtx),
				},
			}...,
		),
	)
}
