// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CreateEnvironmentReq struct {
	ProjectId   string `json:"projectId"`
	Name        string `json:"name"`
	DisplayName string `json:"displayName"`
}

type CreateEnvironmentResp struct {
	Id          string `json:"id"`
	ProjectId   string `json:"projectId"`
	Name        string `json:"name"`
	DisplayName string `json:"displayName"`
}

type CreateProjectReq struct {
	TenantId string `json:"tenantId"`
	Name     string `json:"name"`
	Key      string `json:"key"`
}

type CreateProjectResp struct {
	Id       string `json:"id"`
	TenantId string `json:"tenantId"`
	Name     string `json:"name"`
	Key      string `json:"key"`
}

type CreateTenantReq struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type CreateTenantResp struct {
	Id   string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type DeleteTenantReq struct {
	TenantId string `json:"tenantId"`
}

type DeleteTenantResp struct {
	Success bool `json:"success"`
}

type EnvironmentItem struct {
	Id          string `json:"id"`
	ProjectId   string `json:"projectId"`
	Name        string `json:"name"`
	DisplayName string `json:"displayName"`
}

type GetTenantReq struct {
	TenantId string `path:"tenantId"`
}

type GetTenantResp struct {
	Id   string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type ListEnvironmentsReq struct {
	ProjectId string `form:"projectId"`
}

type ListEnvironmentsResp struct {
	Items []EnvironmentItem `json:"items"`
}

type ListProjectsReq struct {
	TenantId string `form:"tenantId"`
}

type ListProjectsResp struct {
	Items []ProjectItem `json:"items"`
}

type MyTenantItem struct {
	Id   string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type MyTenantsReq struct {
	MemberId string `header:"x-uid"`
}

type MyTenantsResp struct {
	Items []MyTenantItem `json:"items"`
}

type ProjectItem struct {
	Id       string `json:"id"`
	TenantId string `json:"tenantId"`
	Name     string `json:"name"`
	Key      string `json:"key"`
}

type UpdateTenantReq struct {
	TenantId string `json:"tenantId"`
	Name     string `json:"name"`
	Slug     string `json:"slug"`
}

type UpdateTenantResp struct {
	Id   string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}
