// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rpc/history.proto

package history

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	MediaType     int64                  `protobuf:"varint,2,opt,name=MediaType,proto3" json:"MediaType,omitempty"`
	MediaID       int64                  `protobuf:"varint,3,opt,name=MediaID,proto3" json:"MediaID,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=Title,proto3" json:"Title,omitempty"`
	Cover         string                 `protobuf:"bytes,5,opt,name=Cover,proto3" json:"Cover,omitempty"`
	AuthorID      int64                  `protobuf:"varint,6,opt,name=AuthorID,proto3" json:"AuthorID,omitempty"`
	ProgressMs    int64                  `protobuf:"varint,7,opt,name=ProgressMs,proto3" json:"ProgressMs,omitempty"`
	DurationMs    int64                  `protobuf:"varint,8,opt,name=DurationMs,proto3" json:"DurationMs,omitempty"`
	Finished      bool                   `protobuf:"varint,9,opt,name=Finished,proto3" json:"Finished,omitempty"`
	Source        int64                  `protobuf:"varint,10,opt,name=Source,proto3" json:"Source,omitempty"`
	Device        string                 `protobuf:"bytes,11,opt,name=Device,proto3" json:"Device,omitempty"`
	Meta          string                 `protobuf:"bytes,12,opt,name=Meta,proto3" json:"Meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordHistoryRequest) Reset() {
	*x = RecordHistoryRequest{}
	mi := &file_rpc_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordHistoryRequest) ProtoMessage() {}

func (x *RecordHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordHistoryRequest.ProtoReflect.Descriptor instead.
func (*RecordHistoryRequest) Descriptor() ([]byte, []int) {
	return file_rpc_history_proto_rawDescGZIP(), []int{0}
}

func (x *RecordHistoryRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *RecordHistoryRequest) GetMediaType() int64 {
	if x != nil {
		return x.MediaType
	}
	return 0
}

func (x *RecordHistoryRequest) GetMediaID() int64 {
	if x != nil {
		return x.MediaID
	}
	return 0
}

func (x *RecordHistoryRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RecordHistoryRequest) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *RecordHistoryRequest) GetAuthorID() int64 {
	if x != nil {
		return x.AuthorID
	}
	return 0
}

func (x *RecordHistoryRequest) GetProgressMs() int64 {
	if x != nil {
		return x.ProgressMs
	}
	return 0
}

func (x *RecordHistoryRequest) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *RecordHistoryRequest) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *RecordHistoryRequest) GetSource() int64 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *RecordHistoryRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *RecordHistoryRequest) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

type HistoryRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	MediaType     int64                  `protobuf:"varint,3,opt,name=MediaType,proto3" json:"MediaType,omitempty"`
	MediaID       int64                  `protobuf:"varint,4,opt,name=MediaID,proto3" json:"MediaID,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=Title,proto3" json:"Title,omitempty"`
	Cover         string                 `protobuf:"bytes,6,opt,name=Cover,proto3" json:"Cover,omitempty"`
	AuthorID      int64                  `protobuf:"varint,7,opt,name=AuthorID,proto3" json:"AuthorID,omitempty"`
	ProgressMs    int64                  `protobuf:"varint,8,opt,name=ProgressMs,proto3" json:"ProgressMs,omitempty"`
	DurationMs    int64                  `protobuf:"varint,9,opt,name=DurationMs,proto3" json:"DurationMs,omitempty"`
	Finished      bool                   `protobuf:"varint,10,opt,name=Finished,proto3" json:"Finished,omitempty"`
	Source        int64                  `protobuf:"varint,11,opt,name=Source,proto3" json:"Source,omitempty"`
	Device        string                 `protobuf:"bytes,12,opt,name=Device,proto3" json:"Device,omitempty"`
	Meta          string                 `protobuf:"bytes,13,opt,name=Meta,proto3" json:"Meta,omitempty"`
	FirstSeenAt   int64                  `protobuf:"varint,14,opt,name=FirstSeenAt,proto3" json:"FirstSeenAt,omitempty"`
	LastSeenAt    int64                  `protobuf:"varint,15,opt,name=LastSeenAt,proto3" json:"LastSeenAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRecord) Reset() {
	*x = HistoryRecord{}
	mi := &file_rpc_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRecord) ProtoMessage() {}

func (x *HistoryRecord) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRecord.ProtoReflect.Descriptor instead.
func (*HistoryRecord) Descriptor() ([]byte, []int) {
	return file_rpc_history_proto_rawDescGZIP(), []int{1}
}

func (x *HistoryRecord) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *HistoryRecord) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *HistoryRecord) GetMediaType() int64 {
	if x != nil {
		return x.MediaType
	}
	return 0
}

func (x *HistoryRecord) GetMediaID() int64 {
	if x != nil {
		return x.MediaID
	}
	return 0
}

func (x *HistoryRecord) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HistoryRecord) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *HistoryRecord) GetAuthorID() int64 {
	if x != nil {
		return x.AuthorID
	}
	return 0
}

func (x *HistoryRecord) GetProgressMs() int64 {
	if x != nil {
		return x.ProgressMs
	}
	return 0
}

func (x *HistoryRecord) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *HistoryRecord) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *HistoryRecord) GetSource() int64 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *HistoryRecord) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *HistoryRecord) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *HistoryRecord) GetFirstSeenAt() int64 {
	if x != nil {
		return x.FirstSeenAt
	}
	return 0
}

func (x *HistoryRecord) GetLastSeenAt() int64 {
	if x != nil {
		return x.LastSeenAt
	}
	return 0
}

type RecordHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *HistoryRecord         `protobuf:"bytes,1,opt,name=Record,proto3" json:"Record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordHistoryResponse) Reset() {
	*x = RecordHistoryResponse{}
	mi := &file_rpc_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordHistoryResponse) ProtoMessage() {}

func (x *RecordHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordHistoryResponse.ProtoReflect.Descriptor instead.
func (*RecordHistoryResponse) Descriptor() ([]byte, []int) {
	return file_rpc_history_proto_rawDescGZIP(), []int{2}
}

func (x *RecordHistoryResponse) GetRecord() *HistoryRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type ListHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	MediaType     int64                  `protobuf:"varint,2,opt,name=MediaType,proto3" json:"MediaType,omitempty"`
	Cursor        int64                  `protobuf:"varint,3,opt,name=Cursor,proto3" json:"Cursor,omitempty"`
	LastID        int64                  `protobuf:"varint,4,opt,name=LastID,proto3" json:"LastID,omitempty"`
	PageSize      int64                  `protobuf:"varint,5,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHistoryRequest) Reset() {
	*x = ListHistoryRequest{}
	mi := &file_rpc_history_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHistoryRequest) ProtoMessage() {}

func (x *ListHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_history_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHistoryRequest.ProtoReflect.Descriptor instead.
func (*ListHistoryRequest) Descriptor() ([]byte, []int) {
	return file_rpc_history_proto_rawDescGZIP(), []int{3}
}

func (x *ListHistoryRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ListHistoryRequest) GetMediaType() int64 {
	if x != nil {
		return x.MediaType
	}
	return 0
}

func (x *ListHistoryRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ListHistoryRequest) GetLastID() int64 {
	if x != nil {
		return x.LastID
	}
	return 0
}

func (x *ListHistoryRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*HistoryRecord       `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	IsEnd         bool                   `protobuf:"varint,2,opt,name=IsEnd,proto3" json:"IsEnd,omitempty"`
	Cursor        int64                  `protobuf:"varint,3,opt,name=Cursor,proto3" json:"Cursor,omitempty"`
	LastID        int64                  `protobuf:"varint,4,opt,name=LastID,proto3" json:"LastID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHistoryResponse) Reset() {
	*x = ListHistoryResponse{}
	mi := &file_rpc_history_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHistoryResponse) ProtoMessage() {}

func (x *ListHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_history_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHistoryResponse.ProtoReflect.Descriptor instead.
func (*ListHistoryResponse) Descriptor() ([]byte, []int) {
	return file_rpc_history_proto_rawDescGZIP(), []int{4}
}

func (x *ListHistoryResponse) GetList() []*HistoryRecord {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListHistoryResponse) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

func (x *ListHistoryResponse) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ListHistoryResponse) GetLastID() int64 {
	if x != nil {
		return x.LastID
	}
	return 0
}

type DeleteHistoryItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	MediaType     int64                  `protobuf:"varint,2,opt,name=MediaType,proto3" json:"MediaType,omitempty"`
	MediaID       int64                  `protobuf:"varint,3,opt,name=MediaID,proto3" json:"MediaID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHistoryItemRequest) Reset() {
	*x = DeleteHistoryItemRequest{}
	mi := &file_rpc_history_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHistoryItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHistoryItemRequest) ProtoMessage() {}

func (x *DeleteHistoryItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_history_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHistoryItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteHistoryItemRequest) Descriptor() ([]byte, []int) {
	return file_rpc_history_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteHistoryItemRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *DeleteHistoryItemRequest) GetMediaType() int64 {
	if x != nil {
		return x.MediaType
	}
	return 0
}

func (x *DeleteHistoryItemRequest) GetMediaID() int64 {
	if x != nil {
		return x.MediaID
	}
	return 0
}

type ClearHistoryByTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	MediaType     int64                  `protobuf:"varint,2,opt,name=MediaType,proto3" json:"MediaType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearHistoryByTypeRequest) Reset() {
	*x = ClearHistoryByTypeRequest{}
	mi := &file_rpc_history_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearHistoryByTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearHistoryByTypeRequest) ProtoMessage() {}

func (x *ClearHistoryByTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_history_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearHistoryByTypeRequest.ProtoReflect.Descriptor instead.
func (*ClearHistoryByTypeRequest) Descriptor() ([]byte, []int) {
	return file_rpc_history_proto_rawDescGZIP(), []int{6}
}

func (x *ClearHistoryByTypeRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ClearHistoryByTypeRequest) GetMediaType() int64 {
	if x != nil {
		return x.MediaType
	}
	return 0
}

type ClearHistoryAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearHistoryAllRequest) Reset() {
	*x = ClearHistoryAllRequest{}
	mi := &file_rpc_history_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearHistoryAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearHistoryAllRequest) ProtoMessage() {}

func (x *ClearHistoryAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_history_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearHistoryAllRequest.ProtoReflect.Descriptor instead.
func (*ClearHistoryAllRequest) Descriptor() ([]byte, []int) {
	return file_rpc_history_proto_rawDescGZIP(), []int{7}
}

func (x *ClearHistoryAllRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_rpc_history_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_history_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_rpc_history_proto_rawDescGZIP(), []int{8}
}

func (x *ActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rpc_history_proto protoreflect.FileDescriptor

const file_rpc_history_proto_rawDesc = "" +
	"\n" +
	"\x11rpc/history.proto\x12\rhistoryclient\"\xce\x02\n" +
	"\x14RecordHistoryRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x03R\x06UserID\x12\x1c\n" +
	"\tMediaType\x18\x02 \x01(\x03R\tMediaType\x12\x18\n" +
	"\aMediaID\x18\x03 \x01(\x03R\aMediaID\x12\x14\n" +
	"\x05Title\x18\x04 \x01(\tR\x05Title\x12\x14\n" +
	"\x05Cover\x18\x05 \x01(\tR\x05Cover\x12\x1a\n" +
	"\bAuthorID\x18\x06 \x01(\x03R\bAuthorID\x12\x1e\n" +
	"\n" +
	"ProgressMs\x18\a \x01(\x03R\n" +
	"ProgressMs\x12\x1e\n" +
	"\n" +
	"DurationMs\x18\b \x01(\x03R\n" +
	"DurationMs\x12\x1a\n" +
	"\bFinished\x18\t \x01(\bR\bFinished\x12\x16\n" +
	"\x06Source\x18\n" +
	" \x01(\x03R\x06Source\x12\x16\n" +
	"\x06Device\x18\v \x01(\tR\x06Device\x12\x12\n" +
	"\x04Meta\x18\f \x01(\tR\x04Meta\"\x99\x03\n" +
	"\rHistoryRecord\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\x03R\x06UserID\x12\x1c\n" +
	"\tMediaType\x18\x03 \x01(\x03R\tMediaType\x12\x18\n" +
	"\aMediaID\x18\x04 \x01(\x03R\aMediaID\x12\x14\n" +
	"\x05Title\x18\x05 \x01(\tR\x05Title\x12\x14\n" +
	"\x05Cover\x18\x06 \x01(\tR\x05Cover\x12\x1a\n" +
	"\bAuthorID\x18\a \x01(\x03R\bAuthorID\x12\x1e\n" +
	"\n" +
	"ProgressMs\x18\b \x01(\x03R\n" +
	"ProgressMs\x12\x1e\n" +
	"\n" +
	"DurationMs\x18\t \x01(\x03R\n" +
	"DurationMs\x12\x1a\n" +
	"\bFinished\x18\n" +
	" \x01(\bR\bFinished\x12\x16\n" +
	"\x06Source\x18\v \x01(\x03R\x06Source\x12\x16\n" +
	"\x06Device\x18\f \x01(\tR\x06Device\x12\x12\n" +
	"\x04Meta\x18\r \x01(\tR\x04Meta\x12 \n" +
	"\vFirstSeenAt\x18\x0e \x01(\x03R\vFirstSeenAt\x12\x1e\n" +
	"\n" +
	"LastSeenAt\x18\x0f \x01(\x03R\n" +
	"LastSeenAt\"M\n" +
	"\x15RecordHistoryResponse\x124\n" +
	"\x06Record\x18\x01 \x01(\v2\x1c.historyclient.HistoryRecordR\x06Record\"\x96\x01\n" +
	"\x12ListHistoryRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x03R\x06UserID\x12\x1c\n" +
	"\tMediaType\x18\x02 \x01(\x03R\tMediaType\x12\x16\n" +
	"\x06Cursor\x18\x03 \x01(\x03R\x06Cursor\x12\x16\n" +
	"\x06LastID\x18\x04 \x01(\x03R\x06LastID\x12\x1a\n" +
	"\bPageSize\x18\x05 \x01(\x03R\bPageSize\"\x8d\x01\n" +
	"\x13ListHistoryResponse\x120\n" +
	"\x04List\x18\x01 \x03(\v2\x1c.historyclient.HistoryRecordR\x04List\x12\x14\n" +
	"\x05IsEnd\x18\x02 \x01(\bR\x05IsEnd\x12\x16\n" +
	"\x06Cursor\x18\x03 \x01(\x03R\x06Cursor\x12\x16\n" +
	"\x06LastID\x18\x04 \x01(\x03R\x06LastID\"j\n" +
	"\x18DeleteHistoryItemRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x03R\x06UserID\x12\x1c\n" +
	"\tMediaType\x18\x02 \x01(\x03R\tMediaType\x12\x18\n" +
	"\aMediaID\x18\x03 \x01(\x03R\aMediaID\"Q\n" +
	"\x19ClearHistoryByTypeRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x03R\x06UserID\x12\x1c\n" +
	"\tMediaType\x18\x02 \x01(\x03R\tMediaType\"0\n" +
	"\x16ClearHistoryAllRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x03R\x06UserID\"D\n" +
	"\x0eActionResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage2\xd0\x03\n" +
	"\aHistory\x12Z\n" +
	"\rRecordHistory\x12#.historyclient.RecordHistoryRequest\x1a$.historyclient.RecordHistoryResponse\x12T\n" +
	"\vListHistory\x12!.historyclient.ListHistoryRequest\x1a\".historyclient.ListHistoryResponse\x12[\n" +
	"\x11DeleteHistoryItem\x12'.historyclient.DeleteHistoryItemRequest\x1a\x1d.historyclient.ActionResponse\x12]\n" +
	"\x12ClearHistoryByType\x12(.historyclient.ClearHistoryByTypeRequest\x1a\x1d.historyclient.ActionResponse\x12W\n" +
	"\x0fClearHistoryAll\x12%.historyclient.ClearHistoryAllRequest\x1a\x1d.historyclient.ActionResponseB\n" +
	"Z\b/historyb\x06proto3"

var (
	file_rpc_history_proto_rawDescOnce sync.Once
	file_rpc_history_proto_rawDescData []byte
)

func file_rpc_history_proto_rawDescGZIP() []byte {
	file_rpc_history_proto_rawDescOnce.Do(func() {
		file_rpc_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_history_proto_rawDesc), len(file_rpc_history_proto_rawDesc)))
	})
	return file_rpc_history_proto_rawDescData
}

var file_rpc_history_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_rpc_history_proto_goTypes = []any{
	(*RecordHistoryRequest)(nil),      // 0: historyclient.RecordHistoryRequest
	(*HistoryRecord)(nil),             // 1: historyclient.HistoryRecord
	(*RecordHistoryResponse)(nil),     // 2: historyclient.RecordHistoryResponse
	(*ListHistoryRequest)(nil),        // 3: historyclient.ListHistoryRequest
	(*ListHistoryResponse)(nil),       // 4: historyclient.ListHistoryResponse
	(*DeleteHistoryItemRequest)(nil),  // 5: historyclient.DeleteHistoryItemRequest
	(*ClearHistoryByTypeRequest)(nil), // 6: historyclient.ClearHistoryByTypeRequest
	(*ClearHistoryAllRequest)(nil),    // 7: historyclient.ClearHistoryAllRequest
	(*ActionResponse)(nil),            // 8: historyclient.ActionResponse
}
var file_rpc_history_proto_depIdxs = []int32{
	1, // 0: historyclient.RecordHistoryResponse.Record:type_name -> historyclient.HistoryRecord
	1, // 1: historyclient.ListHistoryResponse.List:type_name -> historyclient.HistoryRecord
	0, // 2: historyclient.History.RecordHistory:input_type -> historyclient.RecordHistoryRequest
	3, // 3: historyclient.History.ListHistory:input_type -> historyclient.ListHistoryRequest
	5, // 4: historyclient.History.DeleteHistoryItem:input_type -> historyclient.DeleteHistoryItemRequest
	6, // 5: historyclient.History.ClearHistoryByType:input_type -> historyclient.ClearHistoryByTypeRequest
	7, // 6: historyclient.History.ClearHistoryAll:input_type -> historyclient.ClearHistoryAllRequest
	2, // 7: historyclient.History.RecordHistory:output_type -> historyclient.RecordHistoryResponse
	4, // 8: historyclient.History.ListHistory:output_type -> historyclient.ListHistoryResponse
	8, // 9: historyclient.History.DeleteHistoryItem:output_type -> historyclient.ActionResponse
	8, // 10: historyclient.History.ClearHistoryByType:output_type -> historyclient.ActionResponse
	8, // 11: historyclient.History.ClearHistoryAll:output_type -> historyclient.ActionResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_history_proto_init() }
func file_rpc_history_proto_init() {
	if File_rpc_history_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_history_proto_rawDesc), len(file_rpc_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_history_proto_goTypes,
		DependencyIndexes: file_rpc_history_proto_depIdxs,
		MessageInfos:      file_rpc_history_proto_msgTypes,
	}.Build()
	File_rpc_history_proto = out.File
	file_rpc_history_proto_goTypes = nil
	file_rpc_history_proto_depIdxs = nil
}
