// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: rpc/history.proto

package history

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	History_RecordHistory_FullMethodName      = "/historyclient.History/RecordHistory"
	History_ListHistory_FullMethodName        = "/historyclient.History/ListHistory"
	History_DeleteHistoryItem_FullMethodName  = "/historyclient.History/DeleteHistoryItem"
	History_ClearHistoryByType_FullMethodName = "/historyclient.History/ClearHistoryByType"
	History_ClearHistoryAll_FullMethodName    = "/historyclient.History/ClearHistoryAll"
)

// HistoryClient is the client API for History service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HistoryClient interface {
	RecordHistory(ctx context.Context, in *RecordHistoryRequest, opts ...grpc.CallOption) (*RecordHistoryResponse, error)
	ListHistory(ctx context.Context, in *ListHistoryRequest, opts ...grpc.CallOption) (*ListHistoryResponse, error)
	DeleteHistoryItem(ctx context.Context, in *DeleteHistoryItemRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	ClearHistoryByType(ctx context.Context, in *ClearHistoryByTypeRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	ClearHistoryAll(ctx context.Context, in *ClearHistoryAllRequest, opts ...grpc.CallOption) (*ActionResponse, error)
}

type historyClient struct {
	cc grpc.ClientConnInterface
}

func NewHistoryClient(cc grpc.ClientConnInterface) HistoryClient {
	return &historyClient{cc}
}

func (c *historyClient) RecordHistory(ctx context.Context, in *RecordHistoryRequest, opts ...grpc.CallOption) (*RecordHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordHistoryResponse)
	err := c.cc.Invoke(ctx, History_RecordHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyClient) ListHistory(ctx context.Context, in *ListHistoryRequest, opts ...grpc.CallOption) (*ListHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHistoryResponse)
	err := c.cc.Invoke(ctx, History_ListHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyClient) DeleteHistoryItem(ctx context.Context, in *DeleteHistoryItemRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, History_DeleteHistoryItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyClient) ClearHistoryByType(ctx context.Context, in *ClearHistoryByTypeRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, History_ClearHistoryByType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyClient) ClearHistoryAll(ctx context.Context, in *ClearHistoryAllRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, History_ClearHistoryAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HistoryServer is the server API for History service.
// All implementations must embed UnimplementedHistoryServer
// for forward compatibility.
type HistoryServer interface {
	RecordHistory(context.Context, *RecordHistoryRequest) (*RecordHistoryResponse, error)
	ListHistory(context.Context, *ListHistoryRequest) (*ListHistoryResponse, error)
	DeleteHistoryItem(context.Context, *DeleteHistoryItemRequest) (*ActionResponse, error)
	ClearHistoryByType(context.Context, *ClearHistoryByTypeRequest) (*ActionResponse, error)
	ClearHistoryAll(context.Context, *ClearHistoryAllRequest) (*ActionResponse, error)
	mustEmbedUnimplementedHistoryServer()
}

// UnimplementedHistoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHistoryServer struct{}

func (UnimplementedHistoryServer) RecordHistory(context.Context, *RecordHistoryRequest) (*RecordHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordHistory not implemented")
}
func (UnimplementedHistoryServer) ListHistory(context.Context, *ListHistoryRequest) (*ListHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHistory not implemented")
}
func (UnimplementedHistoryServer) DeleteHistoryItem(context.Context, *DeleteHistoryItemRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteHistoryItem not implemented")
}
func (UnimplementedHistoryServer) ClearHistoryByType(context.Context, *ClearHistoryByTypeRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearHistoryByType not implemented")
}
func (UnimplementedHistoryServer) ClearHistoryAll(context.Context, *ClearHistoryAllRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearHistoryAll not implemented")
}
func (UnimplementedHistoryServer) mustEmbedUnimplementedHistoryServer() {}
func (UnimplementedHistoryServer) testEmbeddedByValue()                 {}

// UnsafeHistoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HistoryServer will
// result in compilation errors.
type UnsafeHistoryServer interface {
	mustEmbedUnimplementedHistoryServer()
}

func RegisterHistoryServer(s grpc.ServiceRegistrar, srv HistoryServer) {
	// If the following call panics, it indicates UnimplementedHistoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&History_ServiceDesc, srv)
}

func _History_RecordHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServer).RecordHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: History_RecordHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServer).RecordHistory(ctx, req.(*RecordHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _History_ListHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServer).ListHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: History_ListHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServer).ListHistory(ctx, req.(*ListHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _History_DeleteHistoryItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHistoryItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServer).DeleteHistoryItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: History_DeleteHistoryItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServer).DeleteHistoryItem(ctx, req.(*DeleteHistoryItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _History_ClearHistoryByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearHistoryByTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServer).ClearHistoryByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: History_ClearHistoryByType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServer).ClearHistoryByType(ctx, req.(*ClearHistoryByTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _History_ClearHistoryAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearHistoryAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServer).ClearHistoryAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: History_ClearHistoryAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServer).ClearHistoryAll(ctx, req.(*ClearHistoryAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// History_ServiceDesc is the grpc.ServiceDesc for History service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var History_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "historyclient.History",
	HandlerType: (*HistoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordHistory",
			Handler:    _History_RecordHistory_Handler,
		},
		{
			MethodName: "ListHistory",
			Handler:    _History_ListHistory_Handler,
		},
		{
			MethodName: "DeleteHistoryItem",
			Handler:    _History_DeleteHistoryItem_Handler,
		},
		{
			MethodName: "ClearHistoryByType",
			Handler:    _History_ClearHistoryByType_Handler,
		},
		{
			MethodName: "ClearHistoryAll",
			Handler:    _History_ClearHistoryAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/history.proto",
}
