// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: im.proto

package imclient

import (
	"context"

	"im/rpc/im"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ActionResponse            = im.ActionResponse
	Conversation              = im.Conversation
	DeliverInternalRequest    = im.DeliverInternalRequest
	DeliverInternalResponse   = im.DeliverInternalResponse
	ListConversationsRequest  = im.ListConversationsRequest
	ListConversationsResponse = im.ListConversationsResponse
	ListMessagesRequest       = im.ListMessagesRequest
	ListMessagesResponse      = im.ListMessagesResponse
	MarkReadRequest           = im.MarkReadRequest
	Message                   = im.Message
	MessagePayload            = im.MessagePayload
	Scope                     = im.Scope
	SendMessageRequest        = im.SendMessageRequest
	SendMessageResponse       = im.SendMessageResponse

	IM interface {
		SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
		ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...grpc.CallOption) (*ListConversationsResponse, error)
		ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error)
		MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*ActionResponse, error)
		DeliverInternal(ctx context.Context, in *DeliverInternalRequest, opts ...grpc.CallOption) (*DeliverInternalResponse, error)
	}

	defaultIM struct {
		cli zrpc.Client
	}
)

func NewIM(cli zrpc.Client) IM {
	return &defaultIM{
		cli: cli,
	}
}

func (m *defaultIM) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	client := im.NewIMClient(m.cli.Conn())
	return client.SendMessage(ctx, in, opts...)
}

func (m *defaultIM) ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...grpc.CallOption) (*ListConversationsResponse, error) {
	client := im.NewIMClient(m.cli.Conn())
	return client.ListConversations(ctx, in, opts...)
}

func (m *defaultIM) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error) {
	client := im.NewIMClient(m.cli.Conn())
	return client.ListMessages(ctx, in, opts...)
}

func (m *defaultIM) MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	client := im.NewIMClient(m.cli.Conn())
	return client.MarkRead(ctx, in, opts...)
}

func (m *defaultIM) DeliverInternal(ctx context.Context, in *DeliverInternalRequest, opts ...grpc.CallOption) (*DeliverInternalResponse, error) {
	client := im.NewIMClient(m.cli.Conn())
	return client.DeliverInternal(ctx, in, opts...)
}
