// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: friend.proto

package friendclient

import (
	"context"

	"friend/rpc/friend"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AcceptRequestReq     = friend.AcceptRequestReq
	AcceptRequestResp    = friend.AcceptRequestResp
	BlockUserReq         = friend.BlockUserReq
	BlockUserResp        = friend.BlockUserResp
	CheckFriendshipReq   = friend.CheckFriendshipReq
	CheckFriendshipResp  = friend.CheckFriendshipResp
	FriendRequestInfo    = friend.FriendRequestInfo
	ListBlockedUsersReq  = friend.ListBlockedUsersReq
	ListBlockedUsersResp = friend.ListBlockedUsersResp
	ListFriendsReq       = friend.ListFriendsReq
	ListFriendsResp      = friend.ListFriendsResp
	ListRequestsReq      = friend.ListRequestsReq
	ListRequestsResp     = friend.ListRequestsResp
	RejectRequestReq     = friend.RejectRequestReq
	RejectRequestResp    = friend.RejectRequestResp
	RemoveFriendReq      = friend.RemoveFriendReq
	RemoveFriendResp     = friend.RemoveFriendResp
	SendRequestReq       = friend.SendRequestReq
	SendRequestResp      = friend.SendRequestResp
	UnblockUserReq       = friend.UnblockUserReq
	UnblockUserResp      = friend.UnblockUserResp

	Friend interface {
		// 好友申请
		SendRequest(ctx context.Context, in *SendRequestReq, opts ...grpc.CallOption) (*SendRequestResp, error)
		AcceptRequest(ctx context.Context, in *AcceptRequestReq, opts ...grpc.CallOption) (*AcceptRequestResp, error)
		RejectRequest(ctx context.Context, in *RejectRequestReq, opts ...grpc.CallOption) (*RejectRequestResp, error)
		ListRequests(ctx context.Context, in *ListRequestsReq, opts ...grpc.CallOption) (*ListRequestsResp, error)
		// 好友管理
		RemoveFriend(ctx context.Context, in *RemoveFriendReq, opts ...grpc.CallOption) (*RemoveFriendResp, error)
		ListFriends(ctx context.Context, in *ListFriendsReq, opts ...grpc.CallOption) (*ListFriendsResp, error)
		CheckFriendship(ctx context.Context, in *CheckFriendshipReq, opts ...grpc.CallOption) (*CheckFriendshipResp, error)
		// 黑名单
		BlockUser(ctx context.Context, in *BlockUserReq, opts ...grpc.CallOption) (*BlockUserResp, error)
		UnblockUser(ctx context.Context, in *UnblockUserReq, opts ...grpc.CallOption) (*UnblockUserResp, error)
		ListBlockedUsers(ctx context.Context, in *ListBlockedUsersReq, opts ...grpc.CallOption) (*ListBlockedUsersResp, error)
	}

	defaultFriend struct {
		cli zrpc.Client
	}
)

func NewFriend(cli zrpc.Client) Friend {
	return &defaultFriend{
		cli: cli,
	}
}

// 好友申请
func (m *defaultFriend) SendRequest(ctx context.Context, in *SendRequestReq, opts ...grpc.CallOption) (*SendRequestResp, error) {
	client := friend.NewFriendClient(m.cli.Conn())
	return client.SendRequest(ctx, in, opts...)
}

func (m *defaultFriend) AcceptRequest(ctx context.Context, in *AcceptRequestReq, opts ...grpc.CallOption) (*AcceptRequestResp, error) {
	client := friend.NewFriendClient(m.cli.Conn())
	return client.AcceptRequest(ctx, in, opts...)
}

func (m *defaultFriend) RejectRequest(ctx context.Context, in *RejectRequestReq, opts ...grpc.CallOption) (*RejectRequestResp, error) {
	client := friend.NewFriendClient(m.cli.Conn())
	return client.RejectRequest(ctx, in, opts...)
}

func (m *defaultFriend) ListRequests(ctx context.Context, in *ListRequestsReq, opts ...grpc.CallOption) (*ListRequestsResp, error) {
	client := friend.NewFriendClient(m.cli.Conn())
	return client.ListRequests(ctx, in, opts...)
}

// 好友管理
func (m *defaultFriend) RemoveFriend(ctx context.Context, in *RemoveFriendReq, opts ...grpc.CallOption) (*RemoveFriendResp, error) {
	client := friend.NewFriendClient(m.cli.Conn())
	return client.RemoveFriend(ctx, in, opts...)
}

func (m *defaultFriend) ListFriends(ctx context.Context, in *ListFriendsReq, opts ...grpc.CallOption) (*ListFriendsResp, error) {
	client := friend.NewFriendClient(m.cli.Conn())
	return client.ListFriends(ctx, in, opts...)
}

func (m *defaultFriend) CheckFriendship(ctx context.Context, in *CheckFriendshipReq, opts ...grpc.CallOption) (*CheckFriendshipResp, error) {
	client := friend.NewFriendClient(m.cli.Conn())
	return client.CheckFriendship(ctx, in, opts...)
}

// 黑名单
func (m *defaultFriend) BlockUser(ctx context.Context, in *BlockUserReq, opts ...grpc.CallOption) (*BlockUserResp, error) {
	client := friend.NewFriendClient(m.cli.Conn())
	return client.BlockUser(ctx, in, opts...)
}

func (m *defaultFriend) UnblockUser(ctx context.Context, in *UnblockUserReq, opts ...grpc.CallOption) (*UnblockUserResp, error) {
	client := friend.NewFriendClient(m.cli.Conn())
	return client.UnblockUser(ctx, in, opts...)
}

func (m *defaultFriend) ListBlockedUsers(ctx context.Context, in *ListBlockedUsersReq, opts ...grpc.CallOption) (*ListBlockedUsersResp, error) {
	client := friend.NewFriendClient(m.cli.Conn())
	return client.ListBlockedUsers(ctx, in, opts...)
}
