// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"platform/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/platform/environment/create",
				Handler: CreateEnvironmentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/platform/environment/list",
				Handler: ListEnvironmentsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/platform/project/create",
				Handler: CreateProjectHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/platform/project/list",
				Handler: ListProjectsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/platform/tenant/:tenantId",
				Handler: GetTenantHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/platform/tenant/create",
				Handler: CreateTenantHandler(serverCtx),
			},
		},
	)
}
