// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rpc/friend.proto

package friend

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendRequestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    int64                  `protobuf:"varint,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      int64                  `protobuf:"varint,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequestReq) Reset() {
	*x = SendRequestReq{}
	mi := &file_rpc_friend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequestReq) ProtoMessage() {}

func (x *SendRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_friend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequestReq.ProtoReflect.Descriptor instead.
func (*SendRequestReq) Descriptor() ([]byte, []int) {
	return file_rpc_friend_proto_rawDescGZIP(), []int{0}
}

func (x *SendRequestReq) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *SendRequestReq) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *SendRequestReq) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *SendRequestReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SendRequestReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendRequestResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     int64                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequestResp) Reset() {
	*x = SendRequestResp{}
	mi := &file_rpc_friend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequestResp) ProtoMessage() {}

func (x *SendRequestResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_friend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequestResp.ProtoReflect.Descriptor instead.
func (*SendRequestResp) Descriptor() ([]byte, []int) {
	return file_rpc_friend_proto_rawDescGZIP(), []int{1}
}

func (x *SendRequestResp) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type AcceptRequestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     int64                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRequestReq) Reset() {
	*x = AcceptRequestReq{}
	mi := &file_rpc_friend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRequestReq) ProtoMessage() {}

func (x *AcceptRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_friend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRequestReq.ProtoReflect.Descriptor instead.
func (*AcceptRequestReq) Descriptor() ([]byte, []int) {
	return file_rpc_friend_proto_rawDescGZIP(), []int{2}
}

func (x *AcceptRequestReq) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *AcceptRequestReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AcceptRequestResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRequestResp) Reset() {
	*x = AcceptRequestResp{}
	mi := &file_rpc_friend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRequestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRequestResp) ProtoMessage() {}

func (x *AcceptRequestResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_friend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRequestResp.ProtoReflect.Descriptor instead.
func (*AcceptRequestResp) Descriptor() ([]byte, []int) {
	return file_rpc_friend_proto_rawDescGZIP(), []int{3}
}

type RejectRequestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     int64                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectRequestReq) Reset() {
	*x = RejectRequestReq{}
	mi := &file_rpc_friend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectRequestReq) ProtoMessage() {}

func (x *RejectRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_friend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectRequestReq.ProtoReflect.Descriptor instead.
func (*RejectRequestReq) Descriptor() ([]byte, []int) {
	return file_rpc_friend_proto_rawDescGZIP(), []int{4}
}

func (x *RejectRequestReq) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *RejectRequestReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RejectRequestResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectRequestResp) Reset() {
	*x = RejectRequestResp{}
	mi := &file_rpc_friend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectRequestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectRequestResp) ProtoMessage() {}

func (x *RejectRequestResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_friend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectRequestResp.ProtoReflect.Descriptor instead.
func (*RejectRequestResp) Descriptor() ([]byte, []int) {
	return file_rpc_friend_proto_rawDescGZIP(), []int{5}
}

type ListRequestsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 0=pending, 1=accepted, 2=rejected
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestsReq) Reset() {
	*x = ListRequestsReq{}
	mi := &file_rpc_friend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestsReq) ProtoMessage() {}

func (x *ListRequestsReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_friend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestsReq.ProtoReflect.Descriptor instead.
func (*ListRequestsReq) Descriptor() ([]byte, []int) {
	return file_rpc_friend_proto_rawDescGZIP(), []int{6}
}

func (x *ListRequestsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListRequestsReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListRequestsReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListRequestsReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FriendRequestInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     int64                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	FromUserId    int64                  `protobuf:"varint,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      int64                  `protobuf:"varint,3,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequestInfo) Reset() {
	*x = FriendRequestInfo{}
	mi := &file_rpc_friend_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequestInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestInfo) ProtoMessage() {}

func (x *FriendRequestInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_friend_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestInfo.ProtoReflect.Descriptor instead.
func (*FriendRequestInfo) Descriptor() ([]byte, []int) {
	return file_rpc_friend_proto_rawDescGZIP(), []int{7}
}

func (x *FriendRequestInfo) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *FriendRequestInfo) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *FriendRequestInfo) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *FriendRequestInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FriendRequestInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FriendRequestInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListRequestsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*FriendRequestInfo   `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestsResp) Reset() {
	*x = ListRequestsResp{}
	mi := &file_rpc_friend_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestsResp) ProtoMessage() {}

func (x *ListRequestsResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_friend_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestsResp.ProtoReflect.Descriptor instead.
func (*ListRequestsResp) Descriptor() ([]byte, []int) {
	return file_rpc_friend_proto_rawDescGZIP(), []int{8}
}

func (x *ListRequestsResp) GetRequests() []*FriendRequestInfo {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *ListRequestsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RemoveFriendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      int64                  `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFriendReq) Reset() {
	*x = RemoveFriendReq{}
	mi := &file_rpc_friend_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendReq) ProtoMessage() {}

func (x *RemoveFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_friend_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendReq.ProtoReflect.Descriptor instead.
func (*RemoveFriendReq) Descriptor() ([]byte, []int) {
	return file_rpc_friend_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveFriendReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveFriendReq) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *RemoveFriendReq) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *RemoveFriendReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type RemoveFriendResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFriendResp) Reset() {
	*x = RemoveFriendResp{}
	mi := &file_rpc_friend_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFriendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendResp) ProtoMessage() {}

func (x *RemoveFriendResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_friend_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendResp.ProtoReflect.Descriptor instead.
func (*RemoveFriendResp) Descriptor() ([]byte, []int) {
	return file_rpc_friend_proto_rawDescGZIP(), []int{10}
}

type ListFriendsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsReq) Reset() {
	*x = ListFriendsReq{}
	mi := &file_rpc_friend_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsReq) ProtoMessage() {}

func (x *ListFriendsReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_friend_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsReq.ProtoReflect.Descriptor instead.
func (*ListFriendsReq) Descriptor() ([]byte, []int) {
	return file_rpc_friend_proto_rawDescGZIP(), []int{11}
}

func (x *ListFriendsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListFriendsReq) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ListFriendsReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListFriendsReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListFriendsReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListFriendsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendIds     []int64                `protobuf:"varint,1,rep,packed,name=friend_ids,json=friendIds,proto3" json:"friend_ids,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsResp) Reset() {
	*x = ListFriendsResp{}
	mi := &file_rpc_friend_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsResp) ProtoMessage() {}

func (x *ListFriendsResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_friend_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsResp.ProtoReflect.Descriptor instead.
func (*ListFriendsResp) Descriptor() ([]byte, []int) {
	return file_rpc_friend_proto_rawDescGZIP(), []int{12}
}

func (x *ListFriendsResp) GetFriendIds() []int64 {
	if x != nil {
		return x.FriendIds
	}
	return nil
}

func (x *ListFriendsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CheckFriendshipReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetId      int64                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFriendshipReq) Reset() {
	*x = CheckFriendshipReq{}
	mi := &file_rpc_friend_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFriendshipReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFriendshipReq) ProtoMessage() {}

func (x *CheckFriendshipReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_friend_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFriendshipReq.ProtoReflect.Descriptor instead.
func (*CheckFriendshipReq) Descriptor() ([]byte, []int) {
	return file_rpc_friend_proto_rawDescGZIP(), []int{13}
}

func (x *CheckFriendshipReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckFriendshipReq) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *CheckFriendshipReq) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CheckFriendshipReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type CheckFriendshipResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFriend      bool                   `protobuf:"varint,1,opt,name=is_friend,json=isFriend,proto3" json:"is_friend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFriendshipResp) Reset() {
	*x = CheckFriendshipResp{}
	mi := &file_rpc_friend_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFriendshipResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFriendshipResp) ProtoMessage() {}

func (x *CheckFriendshipResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_friend_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFriendshipResp.ProtoReflect.Descriptor instead.
func (*CheckFriendshipResp) Descriptor() ([]byte, []int) {
	return file_rpc_friend_proto_rawDescGZIP(), []int{14}
}

func (x *CheckFriendshipResp) GetIsFriend() bool {
	if x != nil {
		return x.IsFriend
	}
	return false
}

type BlockUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BlockedUserId int64                  `protobuf:"varint,2,opt,name=blocked_user_id,json=blockedUserId,proto3" json:"blocked_user_id,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockUserReq) Reset() {
	*x = BlockUserReq{}
	mi := &file_rpc_friend_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUserReq) ProtoMessage() {}

func (x *BlockUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_friend_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUserReq.ProtoReflect.Descriptor instead.
func (*BlockUserReq) Descriptor() ([]byte, []int) {
	return file_rpc_friend_proto_rawDescGZIP(), []int{15}
}

func (x *BlockUserReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BlockUserReq) GetBlockedUserId() int64 {
	if x != nil {
		return x.BlockedUserId
	}
	return 0
}

func (x *BlockUserReq) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *BlockUserReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type BlockUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockUserResp) Reset() {
	*x = BlockUserResp{}
	mi := &file_rpc_friend_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUserResp) ProtoMessage() {}

func (x *BlockUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_friend_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUserResp.ProtoReflect.Descriptor instead.
func (*BlockUserResp) Descriptor() ([]byte, []int) {
	return file_rpc_friend_proto_rawDescGZIP(), []int{16}
}

type UnblockUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BlockedUserId int64                  `protobuf:"varint,2,opt,name=blocked_user_id,json=blockedUserId,proto3" json:"blocked_user_id,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockUserReq) Reset() {
	*x = UnblockUserReq{}
	mi := &file_rpc_friend_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockUserReq) ProtoMessage() {}

func (x *UnblockUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_friend_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockUserReq.ProtoReflect.Descriptor instead.
func (*UnblockUserReq) Descriptor() ([]byte, []int) {
	return file_rpc_friend_proto_rawDescGZIP(), []int{17}
}

func (x *UnblockUserReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnblockUserReq) GetBlockedUserId() int64 {
	if x != nil {
		return x.BlockedUserId
	}
	return 0
}

func (x *UnblockUserReq) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *UnblockUserReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type UnblockUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockUserResp) Reset() {
	*x = UnblockUserResp{}
	mi := &file_rpc_friend_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockUserResp) ProtoMessage() {}

func (x *UnblockUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_friend_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockUserResp.ProtoReflect.Descriptor instead.
func (*UnblockUserResp) Descriptor() ([]byte, []int) {
	return file_rpc_friend_proto_rawDescGZIP(), []int{18}
}

type ListBlockedUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlockedUsersReq) Reset() {
	*x = ListBlockedUsersReq{}
	mi := &file_rpc_friend_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlockedUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlockedUsersReq) ProtoMessage() {}

func (x *ListBlockedUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_friend_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlockedUsersReq.ProtoReflect.Descriptor instead.
func (*ListBlockedUsersReq) Descriptor() ([]byte, []int) {
	return file_rpc_friend_proto_rawDescGZIP(), []int{19}
}

func (x *ListBlockedUsersReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListBlockedUsersReq) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ListBlockedUsersReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListBlockedUsersReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListBlockedUsersReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListBlockedUsersResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BlockedUserIds []int64                `protobuf:"varint,1,rep,packed,name=blocked_user_ids,json=blockedUserIds,proto3" json:"blocked_user_ids,omitempty"`
	Total          int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListBlockedUsersResp) Reset() {
	*x = ListBlockedUsersResp{}
	mi := &file_rpc_friend_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlockedUsersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlockedUsersResp) ProtoMessage() {}

func (x *ListBlockedUsersResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_friend_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlockedUsersResp.ProtoReflect.Descriptor instead.
func (*ListBlockedUsersResp) Descriptor() ([]byte, []int) {
	return file_rpc_friend_proto_rawDescGZIP(), []int{20}
}

func (x *ListBlockedUsersResp) GetBlockedUserIds() []int64 {
	if x != nil {
		return x.BlockedUserIds
	}
	return nil
}

func (x *ListBlockedUsersResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_rpc_friend_proto protoreflect.FileDescriptor

const file_rpc_friend_proto_rawDesc = "" +
	"\n" +
	"\x10rpc/friend.proto\x12\ffriendclient\"\x9f\x01\n" +
	"\x0eSendRequestReq\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\x03R\btoUserId\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"0\n" +
	"\x0fSendRequestResp\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x03R\trequestId\"J\n" +
	"\x10AcceptRequestReq\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x03R\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x13\n" +
	"\x11AcceptRequestResp\"J\n" +
	"\x10RejectRequestReq\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x03R\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x13\n" +
	"\x11RejectRequestResp\"p\n" +
	"\x0fListRequestsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xc3\x01\n" +
	"\x11FriendRequestInfo\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x03R\trequestId\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x03 \x01(\x03R\btoUserId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"e\n" +
	"\x10ListRequestsResp\x12;\n" +
	"\brequests\x18\x01 \x03(\v2\x1f.friendclient.FriendRequestInfoR\brequests\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"|\n" +
	"\x0fRemoveFriendReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\x03R\bfriendId\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\"\x12\n" +
	"\x10RemoveFriendResp\"\x8c\x01\n" +
	"\x0eListFriendsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"F\n" +
	"\x0fListFriendsResp\x12\x1d\n" +
	"\n" +
	"friend_ids\x18\x01 \x03(\x03R\tfriendIds\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x7f\n" +
	"\x12CheckFriendshipReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x03R\btargetId\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\"2\n" +
	"\x13CheckFriendshipResp\x12\x1b\n" +
	"\tis_friend\x18\x01 \x01(\bR\bisFriend\"\x84\x01\n" +
	"\fBlockUserReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12&\n" +
	"\x0fblocked_user_id\x18\x02 \x01(\x03R\rblockedUserId\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\"\x0f\n" +
	"\rBlockUserResp\"\x86\x01\n" +
	"\x0eUnblockUserReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12&\n" +
	"\x0fblocked_user_id\x18\x02 \x01(\x03R\rblockedUserId\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\"\x11\n" +
	"\x0fUnblockUserResp\"\x91\x01\n" +
	"\x13ListBlockedUsersReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"V\n" +
	"\x14ListBlockedUsersResp\x12(\n" +
	"\x10blocked_user_ids\x18\x01 \x03(\x03R\x0eblockedUserIds\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xa7\x06\n" +
	"\x06Friend\x12J\n" +
	"\vSendRequest\x12\x1c.friendclient.SendRequestReq\x1a\x1d.friendclient.SendRequestResp\x12P\n" +
	"\rAcceptRequest\x12\x1e.friendclient.AcceptRequestReq\x1a\x1f.friendclient.AcceptRequestResp\x12P\n" +
	"\rRejectRequest\x12\x1e.friendclient.RejectRequestReq\x1a\x1f.friendclient.RejectRequestResp\x12M\n" +
	"\fListRequests\x12\x1d.friendclient.ListRequestsReq\x1a\x1e.friendclient.ListRequestsResp\x12M\n" +
	"\fRemoveFriend\x12\x1d.friendclient.RemoveFriendReq\x1a\x1e.friendclient.RemoveFriendResp\x12J\n" +
	"\vListFriends\x12\x1c.friendclient.ListFriendsReq\x1a\x1d.friendclient.ListFriendsResp\x12V\n" +
	"\x0fCheckFriendship\x12 .friendclient.CheckFriendshipReq\x1a!.friendclient.CheckFriendshipResp\x12D\n" +
	"\tBlockUser\x12\x1a.friendclient.BlockUserReq\x1a\x1b.friendclient.BlockUserResp\x12J\n" +
	"\vUnblockUser\x12\x1c.friendclient.UnblockUserReq\x1a\x1d.friendclient.UnblockUserResp\x12Y\n" +
	"\x10ListBlockedUsers\x12!.friendclient.ListBlockedUsersReq\x1a\".friendclient.ListBlockedUsersRespB\tZ\a/friendb\x06proto3"

var (
	file_rpc_friend_proto_rawDescOnce sync.Once
	file_rpc_friend_proto_rawDescData []byte
)

func file_rpc_friend_proto_rawDescGZIP() []byte {
	file_rpc_friend_proto_rawDescOnce.Do(func() {
		file_rpc_friend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_friend_proto_rawDesc), len(file_rpc_friend_proto_rawDesc)))
	})
	return file_rpc_friend_proto_rawDescData
}

var file_rpc_friend_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_rpc_friend_proto_goTypes = []any{
	(*SendRequestReq)(nil),       // 0: friendclient.SendRequestReq
	(*SendRequestResp)(nil),      // 1: friendclient.SendRequestResp
	(*AcceptRequestReq)(nil),     // 2: friendclient.AcceptRequestReq
	(*AcceptRequestResp)(nil),    // 3: friendclient.AcceptRequestResp
	(*RejectRequestReq)(nil),     // 4: friendclient.RejectRequestReq
	(*RejectRequestResp)(nil),    // 5: friendclient.RejectRequestResp
	(*ListRequestsReq)(nil),      // 6: friendclient.ListRequestsReq
	(*FriendRequestInfo)(nil),    // 7: friendclient.FriendRequestInfo
	(*ListRequestsResp)(nil),     // 8: friendclient.ListRequestsResp
	(*RemoveFriendReq)(nil),      // 9: friendclient.RemoveFriendReq
	(*RemoveFriendResp)(nil),     // 10: friendclient.RemoveFriendResp
	(*ListFriendsReq)(nil),       // 11: friendclient.ListFriendsReq
	(*ListFriendsResp)(nil),      // 12: friendclient.ListFriendsResp
	(*CheckFriendshipReq)(nil),   // 13: friendclient.CheckFriendshipReq
	(*CheckFriendshipResp)(nil),  // 14: friendclient.CheckFriendshipResp
	(*BlockUserReq)(nil),         // 15: friendclient.BlockUserReq
	(*BlockUserResp)(nil),        // 16: friendclient.BlockUserResp
	(*UnblockUserReq)(nil),       // 17: friendclient.UnblockUserReq
	(*UnblockUserResp)(nil),      // 18: friendclient.UnblockUserResp
	(*ListBlockedUsersReq)(nil),  // 19: friendclient.ListBlockedUsersReq
	(*ListBlockedUsersResp)(nil), // 20: friendclient.ListBlockedUsersResp
}
var file_rpc_friend_proto_depIdxs = []int32{
	7,  // 0: friendclient.ListRequestsResp.requests:type_name -> friendclient.FriendRequestInfo
	0,  // 1: friendclient.Friend.SendRequest:input_type -> friendclient.SendRequestReq
	2,  // 2: friendclient.Friend.AcceptRequest:input_type -> friendclient.AcceptRequestReq
	4,  // 3: friendclient.Friend.RejectRequest:input_type -> friendclient.RejectRequestReq
	6,  // 4: friendclient.Friend.ListRequests:input_type -> friendclient.ListRequestsReq
	9,  // 5: friendclient.Friend.RemoveFriend:input_type -> friendclient.RemoveFriendReq
	11, // 6: friendclient.Friend.ListFriends:input_type -> friendclient.ListFriendsReq
	13, // 7: friendclient.Friend.CheckFriendship:input_type -> friendclient.CheckFriendshipReq
	15, // 8: friendclient.Friend.BlockUser:input_type -> friendclient.BlockUserReq
	17, // 9: friendclient.Friend.UnblockUser:input_type -> friendclient.UnblockUserReq
	19, // 10: friendclient.Friend.ListBlockedUsers:input_type -> friendclient.ListBlockedUsersReq
	1,  // 11: friendclient.Friend.SendRequest:output_type -> friendclient.SendRequestResp
	3,  // 12: friendclient.Friend.AcceptRequest:output_type -> friendclient.AcceptRequestResp
	5,  // 13: friendclient.Friend.RejectRequest:output_type -> friendclient.RejectRequestResp
	8,  // 14: friendclient.Friend.ListRequests:output_type -> friendclient.ListRequestsResp
	10, // 15: friendclient.Friend.RemoveFriend:output_type -> friendclient.RemoveFriendResp
	12, // 16: friendclient.Friend.ListFriends:output_type -> friendclient.ListFriendsResp
	14, // 17: friendclient.Friend.CheckFriendship:output_type -> friendclient.CheckFriendshipResp
	16, // 18: friendclient.Friend.BlockUser:output_type -> friendclient.BlockUserResp
	18, // 19: friendclient.Friend.UnblockUser:output_type -> friendclient.UnblockUserResp
	20, // 20: friendclient.Friend.ListBlockedUsers:output_type -> friendclient.ListBlockedUsersResp
	11, // [11:21] is the sub-list for method output_type
	1,  // [1:11] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_friend_proto_init() }
func file_rpc_friend_proto_init() {
	if File_rpc_friend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_friend_proto_rawDesc), len(file_rpc_friend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_friend_proto_goTypes,
		DependencyIndexes: file_rpc_friend_proto_depIdxs,
		MessageInfos:      file_rpc_friend_proto_msgTypes,
	}.Build()
	File_rpc_friend_proto = out.File
	file_rpc_friend_proto_goTypes = nil
	file_rpc_friend_proto_depIdxs = nil
}
