// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package device_shadow

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DeviceShadowClient is the client API for DeviceShadow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceShadowClient interface {
	GetShadow(ctx context.Context, in *GetShadowRequest, opts ...grpc.CallOption) (*GetShadowResponse, error)
	UpdateShadow(ctx context.Context, in *UpdateShadowRequest, opts ...grpc.CallOption) (*UpdateShadowResponse, error)
	ReportState(ctx context.Context, in *ReportStateRequest, opts ...grpc.CallOption) (*ReportStateResponse, error)
	DeleteShadow(ctx context.Context, in *DeleteShadowRequest, opts ...grpc.CallOption) (*DeleteShadowResponse, error)
	GetDelta(ctx context.Context, in *GetDeltaRequest, opts ...grpc.CallOption) (*GetDeltaResponse, error)
}

type deviceShadowClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceShadowClient(cc grpc.ClientConnInterface) DeviceShadowClient {
	return &deviceShadowClient{cc}
}

func (c *deviceShadowClient) GetShadow(ctx context.Context, in *GetShadowRequest, opts ...grpc.CallOption) (*GetShadowResponse, error) {
	out := new(GetShadowResponse)
	err := c.cc.Invoke(ctx, "/device_shadowclient.DeviceShadow/GetShadow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceShadowClient) UpdateShadow(ctx context.Context, in *UpdateShadowRequest, opts ...grpc.CallOption) (*UpdateShadowResponse, error) {
	out := new(UpdateShadowResponse)
	err := c.cc.Invoke(ctx, "/device_shadowclient.DeviceShadow/UpdateShadow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceShadowClient) ReportState(ctx context.Context, in *ReportStateRequest, opts ...grpc.CallOption) (*ReportStateResponse, error) {
	out := new(ReportStateResponse)
	err := c.cc.Invoke(ctx, "/device_shadowclient.DeviceShadow/ReportState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceShadowClient) DeleteShadow(ctx context.Context, in *DeleteShadowRequest, opts ...grpc.CallOption) (*DeleteShadowResponse, error) {
	out := new(DeleteShadowResponse)
	err := c.cc.Invoke(ctx, "/device_shadowclient.DeviceShadow/DeleteShadow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceShadowClient) GetDelta(ctx context.Context, in *GetDeltaRequest, opts ...grpc.CallOption) (*GetDeltaResponse, error) {
	out := new(GetDeltaResponse)
	err := c.cc.Invoke(ctx, "/device_shadowclient.DeviceShadow/GetDelta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceShadowServer is the server API for DeviceShadow service.
// All implementations must embed UnimplementedDeviceShadowServer
// for forward compatibility
type DeviceShadowServer interface {
	GetShadow(context.Context, *GetShadowRequest) (*GetShadowResponse, error)
	UpdateShadow(context.Context, *UpdateShadowRequest) (*UpdateShadowResponse, error)
	ReportState(context.Context, *ReportStateRequest) (*ReportStateResponse, error)
	DeleteShadow(context.Context, *DeleteShadowRequest) (*DeleteShadowResponse, error)
	GetDelta(context.Context, *GetDeltaRequest) (*GetDeltaResponse, error)
	mustEmbedUnimplementedDeviceShadowServer()
}

// UnimplementedDeviceShadowServer must be embedded to have forward compatible implementations.
type UnimplementedDeviceShadowServer struct {
}

func (UnimplementedDeviceShadowServer) GetShadow(context.Context, *GetShadowRequest) (*GetShadowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShadow not implemented")
}
func (UnimplementedDeviceShadowServer) UpdateShadow(context.Context, *UpdateShadowRequest) (*UpdateShadowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateShadow not implemented")
}
func (UnimplementedDeviceShadowServer) ReportState(context.Context, *ReportStateRequest) (*ReportStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportState not implemented")
}
func (UnimplementedDeviceShadowServer) DeleteShadow(context.Context, *DeleteShadowRequest) (*DeleteShadowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteShadow not implemented")
}
func (UnimplementedDeviceShadowServer) GetDelta(context.Context, *GetDeltaRequest) (*GetDeltaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDelta not implemented")
}
func (UnimplementedDeviceShadowServer) mustEmbedUnimplementedDeviceShadowServer() {}

// UnsafeDeviceShadowServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceShadowServer will
// result in compilation errors.
type UnsafeDeviceShadowServer interface {
	mustEmbedUnimplementedDeviceShadowServer()
}

func RegisterDeviceShadowServer(s grpc.ServiceRegistrar, srv DeviceShadowServer) {
	s.RegisterService(&DeviceShadow_ServiceDesc, srv)
}

func _DeviceShadow_GetShadow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShadowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceShadowServer).GetShadow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/device_shadowclient.DeviceShadow/GetShadow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceShadowServer).GetShadow(ctx, req.(*GetShadowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceShadow_UpdateShadow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateShadowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceShadowServer).UpdateShadow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/device_shadowclient.DeviceShadow/UpdateShadow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceShadowServer).UpdateShadow(ctx, req.(*UpdateShadowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceShadow_ReportState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceShadowServer).ReportState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/device_shadowclient.DeviceShadow/ReportState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceShadowServer).ReportState(ctx, req.(*ReportStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceShadow_DeleteShadow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShadowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceShadowServer).DeleteShadow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/device_shadowclient.DeviceShadow/DeleteShadow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceShadowServer).DeleteShadow(ctx, req.(*DeleteShadowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceShadow_GetDelta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeltaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceShadowServer).GetDelta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/device_shadowclient.DeviceShadow/GetDelta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceShadowServer).GetDelta(ctx, req.(*GetDeltaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceShadow_ServiceDesc is the grpc.ServiceDesc for DeviceShadow service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceShadow_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "device_shadowclient.DeviceShadow",
	HandlerType: (*DeviceShadowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetShadow",
			Handler:    _DeviceShadow_GetShadow_Handler,
		},
		{
			MethodName: "UpdateShadow",
			Handler:    _DeviceShadow_UpdateShadow_Handler,
		},
		{
			MethodName: "ReportState",
			Handler:    _DeviceShadow_ReportState_Handler,
		},
		{
			MethodName: "DeleteShadow",
			Handler:    _DeviceShadow_DeleteShadow_Handler,
		},
		{
			MethodName: "GetDelta",
			Handler:    _DeviceShadow_GetDelta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "device_shadow.proto",
}
