// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: device_shadow.proto

package deviceshadow

import (
	"context"

	"game/server/device_shadow/rpc/device_shadow"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeleteShadowRequest  = device_shadow.DeleteShadowRequest
	DeleteShadowResponse = device_shadow.DeleteShadowResponse
	GetDeltaRequest      = device_shadow.GetDeltaRequest
	GetDeltaResponse     = device_shadow.GetDeltaResponse
	GetShadowRequest     = device_shadow.GetShadowRequest
	GetShadowResponse    = device_shadow.GetShadowResponse
	ReportStateRequest   = device_shadow.ReportStateRequest
	ReportStateResponse  = device_shadow.ReportStateResponse
	ShadowState          = device_shadow.ShadowState
	UpdateShadowRequest  = device_shadow.UpdateShadowRequest
	UpdateShadowResponse = device_shadow.UpdateShadowResponse

	DeviceShadow interface {
		GetShadow(ctx context.Context, in *GetShadowRequest, opts ...grpc.CallOption) (*GetShadowResponse, error)
		UpdateShadow(ctx context.Context, in *UpdateShadowRequest, opts ...grpc.CallOption) (*UpdateShadowResponse, error)
		ReportState(ctx context.Context, in *ReportStateRequest, opts ...grpc.CallOption) (*ReportStateResponse, error)
		DeleteShadow(ctx context.Context, in *DeleteShadowRequest, opts ...grpc.CallOption) (*DeleteShadowResponse, error)
		GetDelta(ctx context.Context, in *GetDeltaRequest, opts ...grpc.CallOption) (*GetDeltaResponse, error)
	}

	defaultDeviceShadow struct {
		cli zrpc.Client
	}
)

func NewDeviceShadow(cli zrpc.Client) DeviceShadow {
	return &defaultDeviceShadow{
		cli: cli,
	}
}

func (m *defaultDeviceShadow) GetShadow(ctx context.Context, in *GetShadowRequest, opts ...grpc.CallOption) (*GetShadowResponse, error) {
	client := device_shadow.NewDeviceShadowClient(m.cli.Conn())
	return client.GetShadow(ctx, in, opts...)
}

func (m *defaultDeviceShadow) UpdateShadow(ctx context.Context, in *UpdateShadowRequest, opts ...grpc.CallOption) (*UpdateShadowResponse, error) {
	client := device_shadow.NewDeviceShadowClient(m.cli.Conn())
	return client.UpdateShadow(ctx, in, opts...)
}

func (m *defaultDeviceShadow) ReportState(ctx context.Context, in *ReportStateRequest, opts ...grpc.CallOption) (*ReportStateResponse, error) {
	client := device_shadow.NewDeviceShadowClient(m.cli.Conn())
	return client.ReportState(ctx, in, opts...)
}

func (m *defaultDeviceShadow) DeleteShadow(ctx context.Context, in *DeleteShadowRequest, opts ...grpc.CallOption) (*DeleteShadowResponse, error) {
	client := device_shadow.NewDeviceShadowClient(m.cli.Conn())
	return client.DeleteShadow(ctx, in, opts...)
}

func (m *defaultDeviceShadow) GetDelta(ctx context.Context, in *GetDeltaRequest, opts ...grpc.CallOption) (*GetDeltaResponse, error) {
	client := device_shadow.NewDeviceShadowClient(m.cli.Conn())
	return client.GetDelta(ctx, in, opts...)
}
