// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0-alpha

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	commentIndexFieldNames          = builder.RawFieldNames(&CommentIndex{})
	commentIndexRows                = strings.Join(commentIndexFieldNames, ",")
	commentIndexRowsExpectAutoSet   = strings.Join(stringx.Remove(commentIndexFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	commentIndexRowsWithPlaceHolder = strings.Join(stringx.Remove(commentIndexFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCommentIndexIDPrefix = "cache:commentIndex:iD:"
)

type (
	commentIndexModel interface {
		Insert(ctx context.Context, data *CommentIndex) (sql.Result, error)
		FindOne(ctx context.Context, iD int64) (*CommentIndex, error)
		Update(ctx context.Context, data *CommentIndex) error
		Delete(ctx context.Context, iD int64) error
	}

	defaultCommentIndexModel struct {
		sqlc.CachedConn
		table string
	}

	CommentIndex struct {
		ID        int64     `db:"id"`
		ObjID     int64     `db:"obj_id"`     // 评论对象ID使用唯一id的话不用type联合主键
		ObjType   int64     `db:"obj_type"`   // 评论对象类型
		MemberID  int64     `db:"member_id"`  // 作者用户ID
		RootID    int64     `db:"root_id"`    // 根评论ID 不为0表示是回复评论
		ReplyID   int64     `db:"reply_id"`   // 被回复的评论ID
		Floor     int64     `db:"floor"`      // 评论楼层
		Count     int64     `db:"count"`      // 挂载子评论总数 可见
		RootCount int64     `db:"root_count"` // 挂载子评论总数 所以
		LikeCount int64     `db:"like_count"` // 点赞数
		HateCount int64     `db:"hate_count"` // 点踩数
		State     int64     `db:"state"`      // 0-正常, 1-隐藏
		Attrs     int64     `db:"attrs"`      // 属性(bit 0-运营置顶, 1-owner置顶 2-大数据)
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newCommentIndexModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCommentIndexModel {
	return &defaultCommentIndexModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`comment_index`",
	}
}

func (m *defaultCommentIndexModel) Delete(ctx context.Context, iD int64) error {
	commentIndexIDKey := fmt.Sprintf("%s%v", cacheCommentIndexIDPrefix, iD)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, iD)
	}, commentIndexIDKey)
	return err
}

func (m *defaultCommentIndexModel) FindOne(ctx context.Context, iD int64) (*CommentIndex, error) {
	commentIndexIDKey := fmt.Sprintf("%s%v", cacheCommentIndexIDPrefix, iD)
	var resp CommentIndex
	err := m.QueryRowCtx(ctx, &resp, commentIndexIDKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", commentIndexRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, iD)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentIndexModel) Insert(ctx context.Context, data *CommentIndex) (sql.Result, error) {
	commentIndexIDKey := fmt.Sprintf("%s%v", cacheCommentIndexIDPrefix, data.ID)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, commentIndexRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ObjID, data.ObjType, data.MemberID, data.RootID, data.ReplyID, data.Floor, data.Count, data.RootCount, data.LikeCount, data.HateCount, data.State, data.Attrs)
	}, commentIndexIDKey)
	return ret, err
}

func (m *defaultCommentIndexModel) Update(ctx context.Context, data *CommentIndex) error {
	commentIndexIDKey := fmt.Sprintf("%s%v", cacheCommentIndexIDPrefix, data.ID)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, commentIndexRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ObjID, data.ObjType, data.MemberID, data.RootID, data.ReplyID, data.Floor, data.Count, data.RootCount, data.LikeCount, data.HateCount, data.State, data.Attrs, data.ID)
	}, commentIndexIDKey)
	return err
}

func (m *defaultCommentIndexModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCommentIndexIDPrefix, primary)
}

func (m *defaultCommentIndexModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", commentIndexRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCommentIndexModel) tableName() string {
	return m.table
}
