// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	commentSubjectFieldNames          = builder.RawFieldNames(&CommentSubject{})
	commentSubjectRows                = strings.Join(commentSubjectFieldNames, ",")
	commentSubjectRowsExpectAutoSet   = strings.Join(stringx.Remove(commentSubjectFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	commentSubjectRowsWithPlaceHolder = strings.Join(stringx.Remove(commentSubjectFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCommentSubjectIdPrefix                     = "cache:commentSubject:id:"
	cacheCommentSubjectStateAttrsMemberIdPrefix     = "cache:commentSubject:state:attrs:memberId:"
	cacheCommentSubjectStateAttrsObjIdObjTypePrefix = "cache:commentSubject:state:attrs:objId:objType:"
)

type (
	commentSubjectModel interface {
		Insert(ctx context.Context, data *CommentSubject) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*CommentSubject, error)
		FindOneByStateAttrsMemberId(ctx context.Context, state uint64, attrs int64, memberId uint64) (*CommentSubject, error)
		FindOneByStateAttrsObjIdObjType(ctx context.Context, state uint64, attrs int64, objId uint64, objType uint64) (*CommentSubject, error)
		Update(ctx context.Context, data *CommentSubject) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCommentSubjectModel struct {
		sqlc.CachedConn
		table string
	}

	CommentSubject struct {
		Id        uint64    `db:"id"`
		ObjId     uint64    `db:"obj_id"`     // 评论对象ID 使用唯一id的话不用type联合主键
		ObjType   uint64    `db:"obj_type"`   // 评论对象类型
		MemberId  uint64    `db:"member_id"`  // 作者用户ID
		Count     int64     `db:"count"`      // 评论总数
		RootCount int64     `db:"root_count"` // 根评论总数
		AllCount  int64     `db:"all_count"`  // 所有评论+回复总数
		State     uint64    `db:"state"`      // 0-正常, 1-隐藏
		Attrs     int64     `db:"attrs"`      // 属性(bit 0-运营置顶, 1-owner置顶 2-大数据)
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newCommentSubjectModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCommentSubjectModel {
	return &defaultCommentSubjectModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`comment_subject`",
	}
}

func (m *defaultCommentSubjectModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	commentSubjectIdKey := fmt.Sprintf("%s%v", cacheCommentSubjectIdPrefix, id)
	commentSubjectStateAttrsMemberIdKey := fmt.Sprintf("%s%v:%v:%v", cacheCommentSubjectStateAttrsMemberIdPrefix, data.State, data.Attrs, data.MemberId)
	commentSubjectStateAttrsObjIdObjTypeKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheCommentSubjectStateAttrsObjIdObjTypePrefix, data.State, data.Attrs, data.ObjId, data.ObjType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, commentSubjectIdKey, commentSubjectStateAttrsMemberIdKey, commentSubjectStateAttrsObjIdObjTypeKey)
	return err
}

func (m *defaultCommentSubjectModel) FindOne(ctx context.Context, id uint64) (*CommentSubject, error) {
	commentSubjectIdKey := fmt.Sprintf("%s%v", cacheCommentSubjectIdPrefix, id)
	var resp CommentSubject
	err := m.QueryRowCtx(ctx, &resp, commentSubjectIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", commentSubjectRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentSubjectModel) FindOneByStateAttrsMemberId(ctx context.Context, state uint64, attrs int64, memberId uint64) (*CommentSubject, error) {
	commentSubjectStateAttrsMemberIdKey := fmt.Sprintf("%s%v:%v:%v", cacheCommentSubjectStateAttrsMemberIdPrefix, state, attrs, memberId)
	var resp CommentSubject
	err := m.QueryRowIndexCtx(ctx, &resp, commentSubjectStateAttrsMemberIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `state` = ? and `attrs` = ? and `member_id` = ? limit 1", commentSubjectRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, state, attrs, memberId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentSubjectModel) FindOneByStateAttrsObjIdObjType(ctx context.Context, state uint64, attrs int64, objId uint64, objType uint64) (*CommentSubject, error) {
	commentSubjectStateAttrsObjIdObjTypeKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheCommentSubjectStateAttrsObjIdObjTypePrefix, state, attrs, objId, objType)
	var resp CommentSubject
	err := m.QueryRowIndexCtx(ctx, &resp, commentSubjectStateAttrsObjIdObjTypeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `state` = ? and `attrs` = ? and `obj_id` = ? and `obj_type` = ? limit 1", commentSubjectRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, state, attrs, objId, objType); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentSubjectModel) Insert(ctx context.Context, data *CommentSubject) (sql.Result, error) {
	commentSubjectIdKey := fmt.Sprintf("%s%v", cacheCommentSubjectIdPrefix, data.Id)
	commentSubjectStateAttrsMemberIdKey := fmt.Sprintf("%s%v:%v:%v", cacheCommentSubjectStateAttrsMemberIdPrefix, data.State, data.Attrs, data.MemberId)
	commentSubjectStateAttrsObjIdObjTypeKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheCommentSubjectStateAttrsObjIdObjTypePrefix, data.State, data.Attrs, data.ObjId, data.ObjType)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, commentSubjectRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ObjId, data.ObjType, data.MemberId, data.Count, data.RootCount, data.AllCount, data.State, data.Attrs)
	}, commentSubjectIdKey, commentSubjectStateAttrsMemberIdKey, commentSubjectStateAttrsObjIdObjTypeKey)
	return ret, err
}

func (m *defaultCommentSubjectModel) Update(ctx context.Context, newData *CommentSubject) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	commentSubjectIdKey := fmt.Sprintf("%s%v", cacheCommentSubjectIdPrefix, data.Id)
	commentSubjectStateAttrsMemberIdKey := fmt.Sprintf("%s%v:%v:%v", cacheCommentSubjectStateAttrsMemberIdPrefix, data.State, data.Attrs, data.MemberId)
	commentSubjectStateAttrsObjIdObjTypeKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheCommentSubjectStateAttrsObjIdObjTypePrefix, data.State, data.Attrs, data.ObjId, data.ObjType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, commentSubjectRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ObjId, newData.ObjType, newData.MemberId, newData.Count, newData.RootCount, newData.AllCount, newData.State, newData.Attrs, newData.Id)
	}, commentSubjectIdKey, commentSubjectStateAttrsMemberIdKey, commentSubjectStateAttrsObjIdObjTypeKey)
	return err
}

func (m *defaultCommentSubjectModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCommentSubjectIdPrefix, primary)
}

func (m *defaultCommentSubjectModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", commentSubjectRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCommentSubjectModel) tableName() string {
	return m.table
}
