// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	commentIndexFieldNames          = builder.RawFieldNames(&CommentIndex{})
	commentIndexRows                = strings.Join(commentIndexFieldNames, ",")
	commentIndexRowsExpectAutoSet   = strings.Join(stringx.Remove(commentIndexFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	commentIndexRowsWithPlaceHolder = strings.Join(stringx.Remove(commentIndexFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCommentIndexIdPrefix                     = "cache:commentIndex:id:"
	cacheCommentIndexStateAttrsObjIdObjTypePrefix = "cache:commentIndex:state:attrs:objId:objType:"
)

type (
	commentIndexModel interface {
		Insert(ctx context.Context, data *CommentIndex) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*CommentIndex, error)
		FindOneByStateAttrsObjIdObjType(ctx context.Context, state uint64, attrs int64, objId uint64, objType uint64) (*CommentIndex, error)
		Update(ctx context.Context, data *CommentIndex) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCommentIndexModel struct {
		sqlc.CachedConn
		table string
	}

	CommentIndex struct {
		ID        uint64    `db:"id"`
		ObjId     uint64    `db:"obj_id"`     // 评论对象ID使用唯一id的话不用type联合主键
		ObjType   uint64    `db:"obj_type"`   // 评论对象类型
		MemberId  uint64    `db:"member_id"`  // 作者用户ID
		RootId    uint64    `db:"root_id"`    // 根评论ID 不为0表示是回复评论
		ReplyId   uint64    `db:"reply_id"`   // 被回复的评论ID
		Floor     uint64    `db:"floor"`      // 评论楼层
		Count     int64     `db:"count"`      // 挂载子评论总数 可见
		RootCount int64     `db:"root_count"` // 挂载子评论总数 所以
		LikeCount int64     `db:"like_count"` // 点赞数
		HateCount int64     `db:"hate_count"` // 点踩数
		State     uint64    `db:"state"`      // 0-正常, 1-隐藏
		Attrs     int64     `db:"attrs"`      // 属性(bit 0-运营置顶, 1-owner置顶 2-大数据)
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newCommentIndexModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCommentIndexModel {
	return &defaultCommentIndexModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`comment_index`",
	}
}

func (m *defaultCommentIndexModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	commentIndexIdKey := fmt.Sprintf("%s%v", cacheCommentIndexIdPrefix, id)
	commentIndexStateAttrsObjIdObjTypeKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheCommentIndexStateAttrsObjIdObjTypePrefix, data.State, data.Attrs, data.ObjId, data.ObjType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, commentIndexIdKey, commentIndexStateAttrsObjIdObjTypeKey)
	return err
}

func (m *defaultCommentIndexModel) FindOne(ctx context.Context, id uint64) (*CommentIndex, error) {
	commentIndexIdKey := fmt.Sprintf("%s%v", cacheCommentIndexIdPrefix, id)
	var resp CommentIndex
	err := m.QueryRowCtx(ctx, &resp, commentIndexIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", commentIndexRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentIndexModel) FindOneByStateAttrsObjIdObjType(ctx context.Context, state uint64, attrs int64, objId uint64, objType uint64) (*CommentIndex, error) {
	commentIndexStateAttrsObjIdObjTypeKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheCommentIndexStateAttrsObjIdObjTypePrefix, state, attrs, objId, objType)
	var resp CommentIndex
	err := m.QueryRowIndexCtx(ctx, &resp, commentIndexStateAttrsObjIdObjTypeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `state` = ? and `attrs` = ? and `obj_id` = ? and `obj_type` = ? limit 1", commentIndexRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, state, attrs, objId, objType); err != nil {
			return nil, err
		}
		return resp.ID, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentIndexModel) Insert(ctx context.Context, data *CommentIndex) (sql.Result, error) {
	commentIndexIdKey := fmt.Sprintf("%s%v", cacheCommentIndexIdPrefix, data.ID)
	commentIndexStateAttrsObjIdObjTypeKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheCommentIndexStateAttrsObjIdObjTypePrefix, data.State, data.Attrs, data.ObjId, data.ObjType)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, commentIndexRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ObjId, data.ObjType, data.MemberId, data.RootId, data.ReplyId, data.Floor, data.Count, data.RootCount, data.LikeCount, data.HateCount, data.State, data.Attrs)
	}, commentIndexIdKey, commentIndexStateAttrsObjIdObjTypeKey)
	return ret, err
}

func (m *defaultCommentIndexModel) Update(ctx context.Context, newData *CommentIndex) error {
	data, err := m.FindOne(ctx, newData.ID)
	if err != nil {
		return err
	}

	commentIndexIdKey := fmt.Sprintf("%s%v", cacheCommentIndexIdPrefix, data.ID)
	commentIndexStateAttrsObjIdObjTypeKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheCommentIndexStateAttrsObjIdObjTypePrefix, data.State, data.Attrs, data.ObjId, data.ObjType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, commentIndexRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ObjId, newData.ObjType, newData.MemberId, newData.RootId, newData.ReplyId, newData.Floor, newData.Count, newData.RootCount, newData.LikeCount, newData.HateCount, newData.State, newData.Attrs, newData.ID)
	}, commentIndexIdKey, commentIndexStateAttrsObjIdObjTypeKey)
	return err
}

func (m *defaultCommentIndexModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCommentIndexIdPrefix, primary)
}

func (m *defaultCommentIndexModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", commentIndexRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCommentIndexModel) tableName() string {
	return m.table
}
