// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	commentContent0FieldNames          = builder.RawFieldNames(&CommentContent0{})
	commentContent0Rows                = strings.Join(commentContent0FieldNames, ",")
	commentContent0RowsExpectAutoSet   = strings.Join(stringx.Remove(commentContent0FieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	commentContent0RowsWithPlaceHolder = strings.Join(stringx.Remove(commentContent0FieldNames, "`comment_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCommentContent0CommentIdPrefix = "cache:commentContent0:commentId:"
)

type (
	commentContent0Model interface {
		Insert(ctx context.Context, data *CommentContent0) (sql.Result, error)
		FindOne(ctx context.Context, commentId uint64) (*CommentContent0, error)
		Update(ctx context.Context, data *CommentContent0) error
		Delete(ctx context.Context, commentId uint64) error
	}

	defaultCommentContent0Model struct {
		sqlc.CachedConn
		table string
	}

	CommentContent0 struct {
		CommentId   uint64    `db:"comment_id"`    // 同评论indx_id
		ObjId       uint64    `db:"obj_id"`        // 评论对象ID使用唯一id的话不用type联合主键
		AtMemberIds string    `db:"at_member_ids"` // at用户ID列表
		Ip          string    `db:"ip"`            // 评论IP
		Platform    uint64    `db:"platform"`      // 评论平台
		Device      string    `db:"device"`        // 评论设备
		Massage     string    `db:"massage"`       // 评论内容
		Meta        string    `db:"meta"`          // 评论元数据 背景 字体
		CreatedAt   time.Time `db:"created_at"`
		UpdatedAt   time.Time `db:"updated_at"`
	}
)

func newCommentContent0Model(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCommentContent0Model {
	return &defaultCommentContent0Model{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`comment_content_0`",
	}
}

func (m *defaultCommentContent0Model) Delete(ctx context.Context, commentId uint64) error {
	commentContent0CommentIdKey := fmt.Sprintf("%s%v", cacheCommentContent0CommentIdPrefix, commentId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `comment_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, commentId)
	}, commentContent0CommentIdKey)
	return err
}

func (m *defaultCommentContent0Model) FindOne(ctx context.Context, commentId uint64) (*CommentContent0, error) {
	commentContent0CommentIdKey := fmt.Sprintf("%s%v", cacheCommentContent0CommentIdPrefix, commentId)
	var resp CommentContent0
	err := m.QueryRowCtx(ctx, &resp, commentContent0CommentIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `comment_id` = ? limit 1", commentContent0Rows, m.table)
		return conn.QueryRowCtx(ctx, v, query, commentId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentContent0Model) Insert(ctx context.Context, data *CommentContent0) (sql.Result, error) {
	commentContent0CommentIdKey := fmt.Sprintf("%s%v", cacheCommentContent0CommentIdPrefix, data.CommentId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, commentContent0RowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CommentId, data.ObjId, data.AtMemberIds, data.Ip, data.Platform, data.Device, data.Massage, data.Meta)
	}, commentContent0CommentIdKey)
	return ret, err
}

func (m *defaultCommentContent0Model) Update(ctx context.Context, data *CommentContent0) error {
	commentContent0CommentIdKey := fmt.Sprintf("%s%v", cacheCommentContent0CommentIdPrefix, data.CommentId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `comment_id` = ?", m.table, commentContent0RowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ObjId, data.AtMemberIds, data.Ip, data.Platform, data.Device, data.Massage, data.Meta, data.CommentId)
	}, commentContent0CommentIdKey)
	return err
}

func (m *defaultCommentContent0Model) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCommentContent0CommentIdPrefix, primary)
}

func (m *defaultCommentContent0Model) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `comment_id` = ? limit 1", commentContent0Rows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCommentContent0Model) tableName() string {
	return m.table
}
