// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	commentIndex0FieldNames          = builder.RawFieldNames(&CommentIndex0{})
	commentIndex0Rows                = strings.Join(commentIndex0FieldNames, ",")
	commentIndex0RowsExpectAutoSet   = strings.Join(stringx.Remove(commentIndex0FieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	commentIndex0RowsWithPlaceHolder = strings.Join(stringx.Remove(commentIndex0FieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCommentIndex0IdPrefix                     = "cache:commentIndex0:id:"
	cacheCommentIndex0StateAttrsObjIdObjTypePrefix = "cache:commentIndex0:state:attrs:objId:objType:"
)

type (
	commentIndex0Model interface {
		Insert(ctx context.Context, data *CommentIndex0) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*CommentIndex0, error)
		FindOneByStateAttrsObjIdObjType(ctx context.Context, state uint64, attrs int64, objId uint64, objType uint64) (*CommentIndex0, error)
		Update(ctx context.Context, data *CommentIndex0) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCommentIndex0Model struct {
		sqlc.CachedConn
		table string
	}

	CommentIndex0 struct {
		Id        uint64    `db:"id"`
		ObjId     uint64    `db:"obj_id"`     // 评论对象ID使用唯一id的话不用type联合主键
		ObjType   uint64    `db:"obj_type"`   // 评论对象类型
		MemberId  uint64    `db:"member_id"`  // 作者用户ID
		RootId    uint64    `db:"root_id"`    // 根评论ID 不为0表示是回复评论
		ReplyId   uint64    `db:"reply_id"`   // 被回复的评论ID
		Floor     uint64    `db:"floor"`      // 评论楼层
		Count     int64     `db:"count"`      // 挂载子评论总数 可见
		RootCount int64     `db:"root_count"` // 挂载子评论总数 所以
		LikeCount int64     `db:"like_count"` // 点赞数
		HateCount int64     `db:"hate_count"` // 点踩数
		State     uint64    `db:"state"`      // 0-正常, 1-隐藏
		Attrs     int64     `db:"attrs"`      // 属性(bit 0-运营置顶, 1-owner置顶 2-大数据)
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newCommentIndex0Model(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCommentIndex0Model {
	return &defaultCommentIndex0Model{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`comment_index_0`",
	}
}

func (m *defaultCommentIndex0Model) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	commentIndex0IdKey := fmt.Sprintf("%s%v", cacheCommentIndex0IdPrefix, id)
	commentIndex0StateAttrsObjIdObjTypeKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheCommentIndex0StateAttrsObjIdObjTypePrefix, data.State, data.Attrs, data.ObjId, data.ObjType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, commentIndex0IdKey, commentIndex0StateAttrsObjIdObjTypeKey)
	return err
}

func (m *defaultCommentIndex0Model) FindOne(ctx context.Context, id uint64) (*CommentIndex0, error) {
	commentIndex0IdKey := fmt.Sprintf("%s%v", cacheCommentIndex0IdPrefix, id)
	var resp CommentIndex0
	err := m.QueryRowCtx(ctx, &resp, commentIndex0IdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", commentIndex0Rows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentIndex0Model) FindOneByStateAttrsObjIdObjType(ctx context.Context, state uint64, attrs int64, objId uint64, objType uint64) (*CommentIndex0, error) {
	commentIndex0StateAttrsObjIdObjTypeKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheCommentIndex0StateAttrsObjIdObjTypePrefix, state, attrs, objId, objType)
	var resp CommentIndex0
	err := m.QueryRowIndexCtx(ctx, &resp, commentIndex0StateAttrsObjIdObjTypeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `state` = ? and `attrs` = ? and `obj_id` = ? and `obj_type` = ? limit 1", commentIndex0Rows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, state, attrs, objId, objType); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentIndex0Model) Insert(ctx context.Context, data *CommentIndex0) (sql.Result, error) {
	commentIndex0IdKey := fmt.Sprintf("%s%v", cacheCommentIndex0IdPrefix, data.Id)
	commentIndex0StateAttrsObjIdObjTypeKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheCommentIndex0StateAttrsObjIdObjTypePrefix, data.State, data.Attrs, data.ObjId, data.ObjType)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, commentIndex0RowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ObjId, data.ObjType, data.MemberId, data.RootId, data.ReplyId, data.Floor, data.Count, data.RootCount, data.LikeCount, data.HateCount, data.State, data.Attrs)
	}, commentIndex0IdKey, commentIndex0StateAttrsObjIdObjTypeKey)
	return ret, err
}

func (m *defaultCommentIndex0Model) Update(ctx context.Context, newData *CommentIndex0) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	commentIndex0IdKey := fmt.Sprintf("%s%v", cacheCommentIndex0IdPrefix, data.Id)
	commentIndex0StateAttrsObjIdObjTypeKey := fmt.Sprintf("%s%v:%v:%v:%v", cacheCommentIndex0StateAttrsObjIdObjTypePrefix, data.State, data.Attrs, data.ObjId, data.ObjType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, commentIndex0RowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ObjId, newData.ObjType, newData.MemberId, newData.RootId, newData.ReplyId, newData.Floor, newData.Count, newData.RootCount, newData.LikeCount, newData.HateCount, newData.State, newData.Attrs, newData.Id)
	}, commentIndex0IdKey, commentIndex0StateAttrsObjIdObjTypeKey)
	return err
}

func (m *defaultCommentIndex0Model) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCommentIndex0IdPrefix, primary)
}

func (m *defaultCommentIndex0Model) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", commentIndex0Rows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCommentIndex0Model) tableName() string {
	return m.table
}
