// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: history.proto

package historyclient

import (
	"context"

	"history/rpc/history"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ActionResponse            = history.ActionResponse
	ClearHistoryAllRequest    = history.ClearHistoryAllRequest
	ClearHistoryByTypeRequest = history.ClearHistoryByTypeRequest
	DeleteHistoryItemRequest  = history.DeleteHistoryItemRequest
	HistoryRecord             = history.HistoryRecord
	ListHistoryRequest        = history.ListHistoryRequest
	ListHistoryResponse       = history.ListHistoryResponse
	RecordHistoryRequest      = history.RecordHistoryRequest
	RecordHistoryResponse     = history.RecordHistoryResponse

	History interface {
		RecordHistory(ctx context.Context, in *RecordHistoryRequest, opts ...grpc.CallOption) (*RecordHistoryResponse, error)
		ListHistory(ctx context.Context, in *ListHistoryRequest, opts ...grpc.CallOption) (*ListHistoryResponse, error)
		DeleteHistoryItem(ctx context.Context, in *DeleteHistoryItemRequest, opts ...grpc.CallOption) (*ActionResponse, error)
		ClearHistoryByType(ctx context.Context, in *ClearHistoryByTypeRequest, opts ...grpc.CallOption) (*ActionResponse, error)
		ClearHistoryAll(ctx context.Context, in *ClearHistoryAllRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	}

	defaultHistory struct {
		cli zrpc.Client
	}
)

func NewHistory(cli zrpc.Client) History {
	return &defaultHistory{
		cli: cli,
	}
}

func (m *defaultHistory) RecordHistory(ctx context.Context, in *RecordHistoryRequest, opts ...grpc.CallOption) (*RecordHistoryResponse, error) {
	client := history.NewHistoryClient(m.cli.Conn())
	return client.RecordHistory(ctx, in, opts...)
}

func (m *defaultHistory) ListHistory(ctx context.Context, in *ListHistoryRequest, opts ...grpc.CallOption) (*ListHistoryResponse, error) {
	client := history.NewHistoryClient(m.cli.Conn())
	return client.ListHistory(ctx, in, opts...)
}

func (m *defaultHistory) DeleteHistoryItem(ctx context.Context, in *DeleteHistoryItemRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	client := history.NewHistoryClient(m.cli.Conn())
	return client.DeleteHistoryItem(ctx, in, opts...)
}

func (m *defaultHistory) ClearHistoryByType(ctx context.Context, in *ClearHistoryByTypeRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	client := history.NewHistoryClient(m.cli.Conn())
	return client.ClearHistoryByType(ctx, in, opts...)
}

func (m *defaultHistory) ClearHistoryAll(ctx context.Context, in *ClearHistoryAllRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	client := history.NewHistoryClient(m.cli.Conn())
	return client.ClearHistoryAll(ctx, in, opts...)
}
