// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rpc/im.proto

package im

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Scope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantID      string                 `protobuf:"bytes,1,opt,name=TenantID,proto3" json:"TenantID,omitempty"`
	ProjectID     string                 `protobuf:"bytes,2,opt,name=ProjectID,proto3" json:"ProjectID,omitempty"`
	Environment   string                 `protobuf:"bytes,3,opt,name=Environment,proto3" json:"Environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scope) Reset() {
	*x = Scope{}
	mi := &file_rpc_im_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scope) ProtoMessage() {}

func (x *Scope) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scope.ProtoReflect.Descriptor instead.
func (*Scope) Descriptor() ([]byte, []int) {
	return file_rpc_im_proto_rawDescGZIP(), []int{0}
}

func (x *Scope) GetTenantID() string {
	if x != nil {
		return x.TenantID
	}
	return ""
}

func (x *Scope) GetProjectID() string {
	if x != nil {
		return x.ProjectID
	}
	return ""
}

func (x *Scope) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

type MessagePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=Json,proto3" json:"Json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagePayload) Reset() {
	*x = MessagePayload{}
	mi := &file_rpc_im_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePayload) ProtoMessage() {}

func (x *MessagePayload) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePayload.ProtoReflect.Descriptor instead.
func (*MessagePayload) Descriptor() ([]byte, []int) {
	return file_rpc_im_proto_rawDescGZIP(), []int{1}
}

func (x *MessagePayload) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=Domain,proto3" json:"Domain,omitempty"`
	Scope         *Scope                 `protobuf:"bytes,2,opt,name=Scope,proto3" json:"Scope,omitempty"`
	Sender        int64                  `protobuf:"varint,3,opt,name=Sender,proto3" json:"Sender,omitempty"`
	Receiver      int64                  `protobuf:"varint,4,opt,name=Receiver,proto3" json:"Receiver,omitempty"`
	MsgType       string                 `protobuf:"bytes,5,opt,name=MsgType,proto3" json:"MsgType,omitempty"`
	Seq           int64                  `protobuf:"varint,6,opt,name=Seq,proto3" json:"Seq,omitempty"`
	Payload       *MessagePayload        `protobuf:"bytes,7,opt,name=Payload,proto3" json:"Payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_rpc_im_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *SendMessageRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *SendMessageRequest) GetSender() int64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *SendMessageRequest) GetReceiver() int64 {
	if x != nil {
		return x.Receiver
	}
	return 0
}

func (x *SendMessageRequest) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *SendMessageRequest) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SendMessageRequest) GetPayload() *MessagePayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendMessageResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	OnlineRecipients int64                  `protobuf:"varint,2,opt,name=OnlineRecipients,proto3" json:"OnlineRecipients,omitempty"`
	StoredOffline    bool                   `protobuf:"varint,3,opt,name=StoredOffline,proto3" json:"StoredOffline,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_rpc_im_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_proto_rawDescGZIP(), []int{3}
}

func (x *SendMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendMessageResponse) GetOnlineRecipients() int64 {
	if x != nil {
		return x.OnlineRecipients
	}
	return 0
}

func (x *SendMessageResponse) GetStoredOffline() bool {
	if x != nil {
		return x.StoredOffline
	}
	return false
}

type ListConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=Domain,proto3" json:"Domain,omitempty"`
	Scope         *Scope                 `protobuf:"bytes,2,opt,name=Scope,proto3" json:"Scope,omitempty"`
	UserID        int64                  `protobuf:"varint,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsRequest) Reset() {
	*x = ListConversationsRequest{}
	mi := &file_rpc_im_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsRequest) ProtoMessage() {}

func (x *ListConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsRequest.ProtoReflect.Descriptor instead.
func (*ListConversationsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_proto_rawDescGZIP(), []int{4}
}

func (x *ListConversationsRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ListConversationsRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *ListConversationsRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type Conversation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Key             string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Domain          string                 `protobuf:"bytes,2,opt,name=Domain,proto3" json:"Domain,omitempty"`
	Scope           *Scope                 `protobuf:"bytes,3,opt,name=Scope,proto3" json:"Scope,omitempty"`
	PeerUserID      int64                  `protobuf:"varint,4,opt,name=PeerUserID,proto3" json:"PeerUserID,omitempty"`
	UnreadCount     int64                  `protobuf:"varint,5,opt,name=UnreadCount,proto3" json:"UnreadCount,omitempty"`
	ReadSeq         int64                  `protobuf:"varint,6,opt,name=ReadSeq,proto3" json:"ReadSeq,omitempty"`
	UpdatedAtUnix   int64                  `protobuf:"varint,7,opt,name=UpdatedAtUnix,proto3" json:"UpdatedAtUnix,omitempty"`
	LastSender      int64                  `protobuf:"varint,8,opt,name=LastSender,proto3" json:"LastSender,omitempty"`
	LastReceiver    int64                  `protobuf:"varint,9,opt,name=LastReceiver,proto3" json:"LastReceiver,omitempty"`
	LastMsgType     string                 `protobuf:"bytes,10,opt,name=LastMsgType,proto3" json:"LastMsgType,omitempty"`
	LastSeq         int64                  `protobuf:"varint,11,opt,name=LastSeq,proto3" json:"LastSeq,omitempty"`
	LastPayloadJson string                 `protobuf:"bytes,12,opt,name=LastPayloadJson,proto3" json:"LastPayloadJson,omitempty"`
	LastSentAtUnix  int64                  `protobuf:"varint,13,opt,name=LastSentAtUnix,proto3" json:"LastSentAtUnix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_rpc_im_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_rpc_im_proto_rawDescGZIP(), []int{5}
}

func (x *Conversation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Conversation) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Conversation) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *Conversation) GetPeerUserID() int64 {
	if x != nil {
		return x.PeerUserID
	}
	return 0
}

func (x *Conversation) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *Conversation) GetReadSeq() int64 {
	if x != nil {
		return x.ReadSeq
	}
	return 0
}

func (x *Conversation) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *Conversation) GetLastSender() int64 {
	if x != nil {
		return x.LastSender
	}
	return 0
}

func (x *Conversation) GetLastReceiver() int64 {
	if x != nil {
		return x.LastReceiver
	}
	return 0
}

func (x *Conversation) GetLastMsgType() string {
	if x != nil {
		return x.LastMsgType
	}
	return ""
}

func (x *Conversation) GetLastSeq() int64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *Conversation) GetLastPayloadJson() string {
	if x != nil {
		return x.LastPayloadJson
	}
	return ""
}

func (x *Conversation) GetLastSentAtUnix() int64 {
	if x != nil {
		return x.LastSentAtUnix
	}
	return 0
}

type ListConversationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*Conversation        `protobuf:"bytes,1,rep,name=Conversations,proto3" json:"Conversations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsResponse) Reset() {
	*x = ListConversationsResponse{}
	mi := &file_rpc_im_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsResponse) ProtoMessage() {}

func (x *ListConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsResponse.ProtoReflect.Descriptor instead.
func (*ListConversationsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_proto_rawDescGZIP(), []int{6}
}

func (x *ListConversationsResponse) GetConversations() []*Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

type ListMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=Domain,proto3" json:"Domain,omitempty"`
	Scope         *Scope                 `protobuf:"bytes,2,opt,name=Scope,proto3" json:"Scope,omitempty"`
	UserID        int64                  `protobuf:"varint,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	PeerUserID    int64                  `protobuf:"varint,4,opt,name=PeerUserID,proto3" json:"PeerUserID,omitempty"`
	Limit         int64                  `protobuf:"varint,5,opt,name=Limit,proto3" json:"Limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesRequest) Reset() {
	*x = ListMessagesRequest{}
	mi := &file_rpc_im_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest) ProtoMessage() {}

func (x *ListMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_proto_rawDescGZIP(), []int{7}
}

func (x *ListMessagesRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ListMessagesRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *ListMessagesRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ListMessagesRequest) GetPeerUserID() int64 {
	if x != nil {
		return x.PeerUserID
	}
	return 0
}

func (x *ListMessagesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=Domain,proto3" json:"Domain,omitempty"`
	Scope         *Scope                 `protobuf:"bytes,2,opt,name=Scope,proto3" json:"Scope,omitempty"`
	Sender        int64                  `protobuf:"varint,3,opt,name=Sender,proto3" json:"Sender,omitempty"`
	Receiver      int64                  `protobuf:"varint,4,opt,name=Receiver,proto3" json:"Receiver,omitempty"`
	MsgType       string                 `protobuf:"bytes,5,opt,name=MsgType,proto3" json:"MsgType,omitempty"`
	Seq           int64                  `protobuf:"varint,6,opt,name=Seq,proto3" json:"Seq,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,7,opt,name=PayloadJson,proto3" json:"PayloadJson,omitempty"`
	SentAtUnix    int64                  `protobuf:"varint,8,opt,name=SentAtUnix,proto3" json:"SentAtUnix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_rpc_im_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_rpc_im_proto_rawDescGZIP(), []int{8}
}

func (x *Message) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Message) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *Message) GetSender() int64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *Message) GetReceiver() int64 {
	if x != nil {
		return x.Receiver
	}
	return 0
}

func (x *Message) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *Message) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Message) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *Message) GetSentAtUnix() int64 {
	if x != nil {
		return x.SentAtUnix
	}
	return 0
}

type ListMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=Messages,proto3" json:"Messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesResponse) Reset() {
	*x = ListMessagesResponse{}
	mi := &file_rpc_im_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResponse) ProtoMessage() {}

func (x *ListMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListMessagesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_proto_rawDescGZIP(), []int{9}
}

func (x *ListMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type MarkReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=Domain,proto3" json:"Domain,omitempty"`
	Scope         *Scope                 `protobuf:"bytes,2,opt,name=Scope,proto3" json:"Scope,omitempty"`
	UserID        int64                  `protobuf:"varint,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	PeerUserID    int64                  `protobuf:"varint,4,opt,name=PeerUserID,proto3" json:"PeerUserID,omitempty"`
	Seq           int64                  `protobuf:"varint,5,opt,name=Seq,proto3" json:"Seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReadRequest) Reset() {
	*x = MarkReadRequest{}
	mi := &file_rpc_im_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadRequest) ProtoMessage() {}

func (x *MarkReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadRequest.ProtoReflect.Descriptor instead.
func (*MarkReadRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_proto_rawDescGZIP(), []int{10}
}

func (x *MarkReadRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *MarkReadRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *MarkReadRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *MarkReadRequest) GetPeerUserID() int64 {
	if x != nil {
		return x.PeerUserID
	}
	return 0
}

func (x *MarkReadRequest) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_rpc_im_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_proto_rawDescGZIP(), []int{11}
}

func (x *ActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeliverInternalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverInternalRequest) Reset() {
	*x = DeliverInternalRequest{}
	mi := &file_rpc_im_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverInternalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverInternalRequest) ProtoMessage() {}

func (x *DeliverInternalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverInternalRequest.ProtoReflect.Descriptor instead.
func (*DeliverInternalRequest) Descriptor() ([]byte, []int) {
	return file_rpc_im_proto_rawDescGZIP(), []int{12}
}

func (x *DeliverInternalRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type DeliverInternalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivered     int64                  `protobuf:"varint,1,opt,name=Delivered,proto3" json:"Delivered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverInternalResponse) Reset() {
	*x = DeliverInternalResponse{}
	mi := &file_rpc_im_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverInternalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverInternalResponse) ProtoMessage() {}

func (x *DeliverInternalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_im_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverInternalResponse.ProtoReflect.Descriptor instead.
func (*DeliverInternalResponse) Descriptor() ([]byte, []int) {
	return file_rpc_im_proto_rawDescGZIP(), []int{13}
}

func (x *DeliverInternalResponse) GetDelivered() int64 {
	if x != nil {
		return x.Delivered
	}
	return 0
}

var File_rpc_im_proto protoreflect.FileDescriptor

const file_rpc_im_proto_rawDesc = "" +
	"\n" +
	"\frpc/im.proto\x12\bimclient\"c\n" +
	"\x05Scope\x12\x1a\n" +
	"\bTenantID\x18\x01 \x01(\tR\bTenantID\x12\x1c\n" +
	"\tProjectID\x18\x02 \x01(\tR\tProjectID\x12 \n" +
	"\vEnvironment\x18\x03 \x01(\tR\vEnvironment\"$\n" +
	"\x0eMessagePayload\x12\x12\n" +
	"\x04Json\x18\x01 \x01(\tR\x04Json\"\xe7\x01\n" +
	"\x12SendMessageRequest\x12\x16\n" +
	"\x06Domain\x18\x01 \x01(\tR\x06Domain\x12%\n" +
	"\x05Scope\x18\x02 \x01(\v2\x0f.imclient.ScopeR\x05Scope\x12\x16\n" +
	"\x06Sender\x18\x03 \x01(\x03R\x06Sender\x12\x1a\n" +
	"\bReceiver\x18\x04 \x01(\x03R\bReceiver\x12\x18\n" +
	"\aMsgType\x18\x05 \x01(\tR\aMsgType\x12\x10\n" +
	"\x03Seq\x18\x06 \x01(\x03R\x03Seq\x122\n" +
	"\aPayload\x18\a \x01(\v2\x18.imclient.MessagePayloadR\aPayload\"\x81\x01\n" +
	"\x13SendMessageResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\x12*\n" +
	"\x10OnlineRecipients\x18\x02 \x01(\x03R\x10OnlineRecipients\x12$\n" +
	"\rStoredOffline\x18\x03 \x01(\bR\rStoredOffline\"q\n" +
	"\x18ListConversationsRequest\x12\x16\n" +
	"\x06Domain\x18\x01 \x01(\tR\x06Domain\x12%\n" +
	"\x05Scope\x18\x02 \x01(\v2\x0f.imclient.ScopeR\x05Scope\x12\x16\n" +
	"\x06UserID\x18\x03 \x01(\x03R\x06UserID\"\xb3\x03\n" +
	"\fConversation\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12\x16\n" +
	"\x06Domain\x18\x02 \x01(\tR\x06Domain\x12%\n" +
	"\x05Scope\x18\x03 \x01(\v2\x0f.imclient.ScopeR\x05Scope\x12\x1e\n" +
	"\n" +
	"PeerUserID\x18\x04 \x01(\x03R\n" +
	"PeerUserID\x12 \n" +
	"\vUnreadCount\x18\x05 \x01(\x03R\vUnreadCount\x12\x18\n" +
	"\aReadSeq\x18\x06 \x01(\x03R\aReadSeq\x12$\n" +
	"\rUpdatedAtUnix\x18\a \x01(\x03R\rUpdatedAtUnix\x12\x1e\n" +
	"\n" +
	"LastSender\x18\b \x01(\x03R\n" +
	"LastSender\x12\"\n" +
	"\fLastReceiver\x18\t \x01(\x03R\fLastReceiver\x12 \n" +
	"\vLastMsgType\x18\n" +
	" \x01(\tR\vLastMsgType\x12\x18\n" +
	"\aLastSeq\x18\v \x01(\x03R\aLastSeq\x12(\n" +
	"\x0fLastPayloadJson\x18\f \x01(\tR\x0fLastPayloadJson\x12&\n" +
	"\x0eLastSentAtUnix\x18\r \x01(\x03R\x0eLastSentAtUnix\"Y\n" +
	"\x19ListConversationsResponse\x12<\n" +
	"\rConversations\x18\x01 \x03(\v2\x16.imclient.ConversationR\rConversations\"\xa2\x01\n" +
	"\x13ListMessagesRequest\x12\x16\n" +
	"\x06Domain\x18\x01 \x01(\tR\x06Domain\x12%\n" +
	"\x05Scope\x18\x02 \x01(\v2\x0f.imclient.ScopeR\x05Scope\x12\x16\n" +
	"\x06UserID\x18\x03 \x01(\x03R\x06UserID\x12\x1e\n" +
	"\n" +
	"PeerUserID\x18\x04 \x01(\x03R\n" +
	"PeerUserID\x12\x14\n" +
	"\x05Limit\x18\x05 \x01(\x03R\x05Limit\"\xea\x01\n" +
	"\aMessage\x12\x16\n" +
	"\x06Domain\x18\x01 \x01(\tR\x06Domain\x12%\n" +
	"\x05Scope\x18\x02 \x01(\v2\x0f.imclient.ScopeR\x05Scope\x12\x16\n" +
	"\x06Sender\x18\x03 \x01(\x03R\x06Sender\x12\x1a\n" +
	"\bReceiver\x18\x04 \x01(\x03R\bReceiver\x12\x18\n" +
	"\aMsgType\x18\x05 \x01(\tR\aMsgType\x12\x10\n" +
	"\x03Seq\x18\x06 \x01(\x03R\x03Seq\x12 \n" +
	"\vPayloadJson\x18\a \x01(\tR\vPayloadJson\x12\x1e\n" +
	"\n" +
	"SentAtUnix\x18\b \x01(\x03R\n" +
	"SentAtUnix\"E\n" +
	"\x14ListMessagesResponse\x12-\n" +
	"\bMessages\x18\x01 \x03(\v2\x11.imclient.MessageR\bMessages\"\x9a\x01\n" +
	"\x0fMarkReadRequest\x12\x16\n" +
	"\x06Domain\x18\x01 \x01(\tR\x06Domain\x12%\n" +
	"\x05Scope\x18\x02 \x01(\v2\x0f.imclient.ScopeR\x05Scope\x12\x16\n" +
	"\x06UserID\x18\x03 \x01(\x03R\x06UserID\x12\x1e\n" +
	"\n" +
	"PeerUserID\x18\x04 \x01(\x03R\n" +
	"PeerUserID\x12\x10\n" +
	"\x03Seq\x18\x05 \x01(\x03R\x03Seq\"D\n" +
	"\x0eActionResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage\"E\n" +
	"\x16DeliverInternalRequest\x12+\n" +
	"\aMessage\x18\x01 \x01(\v2\x11.imclient.MessageR\aMessage\"7\n" +
	"\x17DeliverInternalResponse\x12\x1c\n" +
	"\tDelivered\x18\x01 \x01(\x03R\tDelivered2\x96\x03\n" +
	"\x02IM\x12J\n" +
	"\vSendMessage\x12\x1c.imclient.SendMessageRequest\x1a\x1d.imclient.SendMessageResponse\x12\\\n" +
	"\x11ListConversations\x12\".imclient.ListConversationsRequest\x1a#.imclient.ListConversationsResponse\x12M\n" +
	"\fListMessages\x12\x1d.imclient.ListMessagesRequest\x1a\x1e.imclient.ListMessagesResponse\x12?\n" +
	"\bMarkRead\x12\x19.imclient.MarkReadRequest\x1a\x18.imclient.ActionResponse\x12V\n" +
	"\x0fDeliverInternal\x12 .imclient.DeliverInternalRequest\x1a!.imclient.DeliverInternalResponseB\x05Z\x03/imb\x06proto3"

var (
	file_rpc_im_proto_rawDescOnce sync.Once
	file_rpc_im_proto_rawDescData []byte
)

func file_rpc_im_proto_rawDescGZIP() []byte {
	file_rpc_im_proto_rawDescOnce.Do(func() {
		file_rpc_im_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_im_proto_rawDesc), len(file_rpc_im_proto_rawDesc)))
	})
	return file_rpc_im_proto_rawDescData
}

var file_rpc_im_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_rpc_im_proto_goTypes = []any{
	(*Scope)(nil),                     // 0: imclient.Scope
	(*MessagePayload)(nil),            // 1: imclient.MessagePayload
	(*SendMessageRequest)(nil),        // 2: imclient.SendMessageRequest
	(*SendMessageResponse)(nil),       // 3: imclient.SendMessageResponse
	(*ListConversationsRequest)(nil),  // 4: imclient.ListConversationsRequest
	(*Conversation)(nil),              // 5: imclient.Conversation
	(*ListConversationsResponse)(nil), // 6: imclient.ListConversationsResponse
	(*ListMessagesRequest)(nil),       // 7: imclient.ListMessagesRequest
	(*Message)(nil),                   // 8: imclient.Message
	(*ListMessagesResponse)(nil),      // 9: imclient.ListMessagesResponse
	(*MarkReadRequest)(nil),           // 10: imclient.MarkReadRequest
	(*ActionResponse)(nil),            // 11: imclient.ActionResponse
	(*DeliverInternalRequest)(nil),    // 12: imclient.DeliverInternalRequest
	(*DeliverInternalResponse)(nil),   // 13: imclient.DeliverInternalResponse
}
var file_rpc_im_proto_depIdxs = []int32{
	0,  // 0: imclient.SendMessageRequest.Scope:type_name -> imclient.Scope
	1,  // 1: imclient.SendMessageRequest.Payload:type_name -> imclient.MessagePayload
	0,  // 2: imclient.ListConversationsRequest.Scope:type_name -> imclient.Scope
	0,  // 3: imclient.Conversation.Scope:type_name -> imclient.Scope
	5,  // 4: imclient.ListConversationsResponse.Conversations:type_name -> imclient.Conversation
	0,  // 5: imclient.ListMessagesRequest.Scope:type_name -> imclient.Scope
	0,  // 6: imclient.Message.Scope:type_name -> imclient.Scope
	8,  // 7: imclient.ListMessagesResponse.Messages:type_name -> imclient.Message
	0,  // 8: imclient.MarkReadRequest.Scope:type_name -> imclient.Scope
	8,  // 9: imclient.DeliverInternalRequest.Message:type_name -> imclient.Message
	2,  // 10: imclient.IM.SendMessage:input_type -> imclient.SendMessageRequest
	4,  // 11: imclient.IM.ListConversations:input_type -> imclient.ListConversationsRequest
	7,  // 12: imclient.IM.ListMessages:input_type -> imclient.ListMessagesRequest
	10, // 13: imclient.IM.MarkRead:input_type -> imclient.MarkReadRequest
	12, // 14: imclient.IM.DeliverInternal:input_type -> imclient.DeliverInternalRequest
	3,  // 15: imclient.IM.SendMessage:output_type -> imclient.SendMessageResponse
	6,  // 16: imclient.IM.ListConversations:output_type -> imclient.ListConversationsResponse
	9,  // 17: imclient.IM.ListMessages:output_type -> imclient.ListMessagesResponse
	11, // 18: imclient.IM.MarkRead:output_type -> imclient.ActionResponse
	13, // 19: imclient.IM.DeliverInternal:output_type -> imclient.DeliverInternalResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_rpc_im_proto_init() }
func file_rpc_im_proto_init() {
	if File_rpc_im_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_im_proto_rawDesc), len(file_rpc_im_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_im_proto_goTypes,
		DependencyIndexes: file_rpc_im_proto_depIdxs,
		MessageInfos:      file_rpc_im_proto_msgTypes,
	}.Build()
	File_rpc_im_proto = out.File
	file_rpc_im_proto_goTypes = nil
	file_rpc_im_proto_depIdxs = nil
}
