package model

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"log"
	"strings"
	"time"

	"github.com/gocql/gocql"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/syncx"
)

var _ CQLUserModel = (*customUserModel)(nil)

var (
	singleFlights = syncx.NewSingleFlight()
	stats         = cache.NewStat("sqlc")
)

type (
	// CQLUserModel is an interface to be customized, add more methods here,
	// and implement the added methods in customUserModel.
	CQLUserModel interface {
		userModel
	}

	customCQLUserModel struct {
		// *defaultUserModel
		cache   cache.Cache
		Session *gocql.Session
		table   string
	}

	// UsersByMobile is the struct for the table users_by_mobile.
	UsersByMobile struct {
		UserID    int64     `db:"user_id"`
		Mobile    string    `db:"mobile"`
		CreatedAt time.Time `db:"created_at"`
	}

	// UsersByEmail is the struct for the table users_by_email.
	UsersByEmail struct {
		UserID    int64     `db:"user_id"`
		Email     string    `db:"email"`
		CreatedAt time.Time `db:"created_at"`
	}

	// UserScan is the struct for the table user_scan.
	UserScan struct {
		Bucket    int64     `db:"bucket"`
		UserID    int64     `db:"user_id"`
		CreatedAt time.Time `db:"created_at"`
	}

	// Buckets is the struct for the table buckets.
	Buckets struct {
		Bucket int64 `db:"bucket"`
	}
)

// NewCQLUserModel returns a model for the database table.
func NewCQLUserModel(session *gocql.Session, cacheConf cache.CacheConf, opts ...cache.Option) UserModel {
	return &customCQLUserModel{
		// defaultUserModel: newDefaultUserModel(conn, cacheConf),
		cache:   cache.New(cacheConf, singleFlights, stats, gocql.ErrNotFound, opts...),
		Session: session,
		table:   "users",
	}
}

// CQLResult is the result of a CQL query.
type CQLResult struct {
	ID                int64
	RowsAffectedCount int64
}

// LastInsertId returns the integer generated by the database
// in response to a command. Typically this will be from an
// "auto increment" column when inserting a new row. Not all
// databases support this feature, and the syntax of such
// statements varies.
func (r *CQLResult) LastInsertId() (int64, error) {
	return r.ID, nil
}

// RowsAffected returns the number of rows affected by an
// update, insert, or delete. Not every database or database
// driver may support this.
func (r *CQLResult) RowsAffected() (int64, error) {
	return r.RowsAffectedCount, nil
}

func buildFileds(a any) string {
	return strings.ReplaceAll(strings.Join(builder.RawFieldNames(a), ","), "`", "")
}

func (u *customCQLUserModel) Insert(ctx context.Context, data *User) (sql.Result, error) {
	batch := u.Session.NewBatch(gocql.LoggedBatch)
	batch.Query(`
        INSERT INTO users (user_id, mobile, email, name, gender, created_at, password)
        VALUES (?, ?, ?, ?, ?, ?, ?)
    `, data.UserID, data.Mobile, data.Email, data.Name, data.Gender, time.Now(), data.Password)

	bucket, _ := json.Number(time.Now().Format("200601")).Int64()
	batch.Query(`
		INSERT INTO user_scan (bucket, user_id, created_at)
		VALUES (?, ?, ?)
	`, bucket, data.UserID, time.Now())

	batch.Query(`
		INSERT INTO buckets (bucket)
		VALUES (?)
	`, bucket)

	if data.Email != "" {
		batch.Query(`
        INSERT INTO users_by_email (email, user_id, created_at)
        VALUES (?, ?, ?)
    `, data.Email, data.UserID, time.Now())
	}
	if data.Mobile != "" {
		batch.Query(`
        INSERT INTO users_by_mobile (mobile, user_id, created_at)
        VALUES (?, ?, ?)
    `, data.Mobile, data.UserID, time.Now())
	}

	err := u.Session.ExecuteBatch(batch)
	if err != nil {
		return nil, err
	}

	return &CQLResult{
		ID:                data.UserID,
		RowsAffectedCount: 1,
	}, nil
}

func (u *customCQLUserModel) FindOne(ctx context.Context, id int64) (*User, error) {
	query := fmt.Sprintf(`select %s from %s where user_id=?`, buildFileds(&User{}), u.TableName())
	var user User
	userIDKey := fmt.Sprintf("%s%v", cacheUserUserIDPrefix, id)
	err := u.cache.TakeCtx(ctx, &user, userIDKey, func(v any) error {
		return u.Session.Query(query, id).Scan(
			&user.UserID,
			&user.Name,
			&user.Gender,
			&user.Mobile,
			&user.Email,
			&user.Password,
			&user.CreatedAt,
			&user.UpdatedAt,
		)
	})
	switch err {
	case nil:
		return &user, nil
	case gocql.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (u *customCQLUserModel) FindOneByMobile(ctx context.Context, mobile string) (*User, error) {
	userMobileKey := fmt.Sprintf("%s%v", cacheUserMobilePrefix, mobile)
	var resp User

	query := fmt.Sprintf(`select %s from %s where mobile=?`, buildFileds(&UsersByMobile{}), UsersByMobile{}.TableName())
	err := u.cache.TakeCtx(ctx, &resp, userMobileKey, func(v any) error {
		err := u.Session.Query(query, mobile).Scan(
			&resp.UserID,
			&resp.Mobile,
			&resp.CreatedAt,
		)
		if err != nil {
			return err
		}

		user, err := u.FindOne(ctx, resp.UserID)
		if err != nil {
			return err
		}
		resp.Gender = user.Gender
		resp.Email = user.Email
		resp.Name = user.Name
		resp.CreatedAt = user.CreatedAt
		resp.Password = user.Password
		resp.UpdatedAt = user.UpdatedAt
		return nil
	})
	switch err {
	case nil:
		return &resp, nil
	case gocql.ErrNotFound:
		return nil, ErrNotFound
	default:
		log.Println(err)
		return nil, err
	}
}

func (u *customCQLUserModel) FindOneByEmail(ctx context.Context, email string) (*User, error) {
	userEmailKey := fmt.Sprintf("%s%v", cacheUserEmailPrefix, email)
	var resp User

	query := fmt.Sprintf(`select %s from %s where email=?`, buildFileds(&UsersByEmail{}), UsersByEmail{}.TableName())
	err := u.cache.TakeCtx(ctx, &resp, userEmailKey, func(v any) error {
		err := u.Session.Query(query, email).Scan(
			&resp.UserID,
			&resp.Email,
			&resp.CreatedAt,
		)
		if err != nil {
			return err
		}

		user, err := u.FindOne(ctx, resp.UserID)
		if err != nil {
			return err
		}
		resp.Gender = user.Gender
		resp.Mobile = user.Mobile
		resp.Name = user.Name
		resp.CreatedAt = user.CreatedAt
		resp.Password = user.Password
		resp.UpdatedAt = user.UpdatedAt
		return nil
	})
	switch err {
	case nil:
		return &resp, nil
	case gocql.ErrNotFound:
		return nil, ErrNotFound
	default:
		log.Println(err)
		return nil, err
	}
}

func (u *customCQLUserModel) Update(ctx context.Context, data *User) error {
	olduser, err := u.FindOne(ctx, data.UserID)
	if err != nil {
		return err
	}

	batch := u.Session.NewBatch(gocql.LoggedBatch)

	// 删除旧 mobile
	if olduser.Mobile != "" && olduser.Mobile != data.Mobile {
		batch.Query(`DELETE FROM %s WHERE mobile=?`, UsersByMobile{}.TableName(), olduser.Mobile)
	}

	// 插入新 mobile
	if data.Mobile != "" && olduser.Mobile != data.Mobile {
		batch.Query(`
            INSERT INTO %s (mobile, user_id, email, name)
            VALUES (?, ?, ?, ?)
        `, UsersByMobile{}.TableName(), data.Mobile, data.UserID, data.Email, data.Name)
	}

	// 删除旧 email
	if olduser.Email != "" && olduser.Email != data.Email {
		batch.Query(`DELETE FROM %s WHERE email=?`, UsersByEmail{}.TableName(), olduser.Email)
	}

	// 插入新 email
	if data.Email != "" && olduser.Email != data.Email {
		batch.Query(`
            INSERT INTO %s (email, user_id, mobile, name)
            VALUES (?, ?, ?, ?)
        `, UsersByEmail{}.TableName(), data.Email, data.UserID, data.Mobile, data.Name)
	}

	// 更新主表
	batch.Query(`
        UPDATE %s
        SET mobile=?, email=?, name=?, update_at=toTimestamp(now())
        WHERE user_id=?
    `, u.TableName(), data.Mobile, data.Email, data.Name, data.UserID)

	err = u.Session.ExecuteBatch(batch)
	if err != nil {
		return err
	}

	return u.cache.DelCtx(ctx, cacheUserUserIDPrefix, cacheUserMobilePrefix)
}

func (u *customCQLUserModel) Delete(ctx context.Context, id int64) error {
	batch := u.Session.NewBatch(gocql.LoggedBatch)
	batch.Query(`DELETE FROM %s WHERE user_id=?`, u.TableName(), id)
	batch.Query(`DELETE FROM %s WHERE user_id=?`, UsersByMobile{}.TableName(), id)
	batch.Query(`DELETE FROM %s WHERE user_id=?`, UsersByEmail{}.TableName(), id)

	// 执行批量删除
	err := u.Session.ExecuteBatch(batch)
	if err != nil {
		return err
	}

	return u.cache.DelCtx(ctx, cacheUserUserIDPrefix, cacheUserMobilePrefix)
}

func (u *customCQLUserModel) TableName() string {
	return u.table
}

// TableName returns the table name of the struct.
func (a Buckets) TableName() string {
	return "buckets"
}

// TableName returns the table name of the struct.
func (a UserScan) TableName() string {
	return "user_scan"
}

// TableName returns the table name of the struct.
func (a UsersByEmail) TableName() string {
	return "users_by_email"
}

// TableName returns the table name of the struct.
func (a UsersByMobile) TableName() string {
	return "users_by_mobile"
}
