// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: im.proto

package server

import (
	"context"

	"im/rpc/im"
	"im/rpc/internal/logic"
	"im/rpc/internal/svc"
)

type IMServer struct {
	svcCtx *svc.ServiceContext
	im.UnimplementedIMServer
}

func NewIMServer(svcCtx *svc.ServiceContext) *IMServer {
	return &IMServer{
		svcCtx: svcCtx,
	}
}

func (s *IMServer) SendMessage(ctx context.Context, in *im.SendMessageRequest) (*im.SendMessageResponse, error) {
	l := logic.NewSendMessageLogic(ctx, s.svcCtx)
	return l.SendMessage(in)
}

func (s *IMServer) ListConversations(ctx context.Context, in *im.ListConversationsRequest) (*im.ListConversationsResponse, error) {
	l := logic.NewListConversationsLogic(ctx, s.svcCtx)
	return l.ListConversations(in)
}

func (s *IMServer) ListMessages(ctx context.Context, in *im.ListMessagesRequest) (*im.ListMessagesResponse, error) {
	l := logic.NewListMessagesLogic(ctx, s.svcCtx)
	return l.ListMessages(in)
}

func (s *IMServer) MarkRead(ctx context.Context, in *im.MarkReadRequest) (*im.ActionResponse, error) {
	l := logic.NewMarkReadLogic(ctx, s.svcCtx)
	return l.MarkRead(in)
}

func (s *IMServer) DeliverInternal(ctx context.Context, in *im.DeliverInternalRequest) (*im.DeliverInternalResponse, error) {
	l := logic.NewDeliverInternalLogic(ctx, s.svcCtx)
	return l.DeliverInternal(in)
}
