// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: device_shadow.proto

package server

import (
	"context"

	"game/server/device_shadow/rpc/device_shadow"
	"game/server/device_shadow/rpc/internal/logic"
	"game/server/device_shadow/rpc/internal/svc"
)

type DeviceShadowServer struct {
	svcCtx *svc.ServiceContext
	device_shadow.UnimplementedDeviceShadowServer
}

func NewDeviceShadowServer(svcCtx *svc.ServiceContext) *DeviceShadowServer {
	return &DeviceShadowServer{
		svcCtx: svcCtx,
	}
}

func (s *DeviceShadowServer) GetShadow(ctx context.Context, in *device_shadow.GetShadowRequest) (*device_shadow.GetShadowResponse, error) {
	l := logic.NewGetShadowLogic(ctx, s.svcCtx)
	return l.GetShadow(in)
}

func (s *DeviceShadowServer) UpdateShadow(ctx context.Context, in *device_shadow.UpdateShadowRequest) (*device_shadow.UpdateShadowResponse, error) {
	l := logic.NewUpdateShadowLogic(ctx, s.svcCtx)
	return l.UpdateShadow(in)
}

func (s *DeviceShadowServer) ReportState(ctx context.Context, in *device_shadow.ReportStateRequest) (*device_shadow.ReportStateResponse, error) {
	l := logic.NewReportStateLogic(ctx, s.svcCtx)
	return l.ReportState(in)
}

func (s *DeviceShadowServer) DeleteShadow(ctx context.Context, in *device_shadow.DeleteShadowRequest) (*device_shadow.DeleteShadowResponse, error) {
	l := logic.NewDeleteShadowLogic(ctx, s.svcCtx)
	return l.DeleteShadow(in)
}

func (s *DeviceShadowServer) GetDelta(ctx context.Context, in *device_shadow.GetDeltaRequest) (*device_shadow.GetDeltaResponse, error) {
	l := logic.NewGetDeltaLogic(ctx, s.svcCtx)
	return l.GetDelta(in)
}
