// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type CommentListRequest struct {
	ObjID    uint64 `form:"obj_id"`    // 评论对象ID
	ObjType  uint64 `form:"obj_type"`  // 评论对象类型
	PageSize uint64 `form:"page_size"` // 页大小
}

type CommentListResponse struct {
	List []CommentResponse
}

type CommentRequest struct {
	ObjID       uint64 `json:"obj_id" form:"obj_id"`               // 评论对象ID
	ObjType     uint64 `json:"obj_type" form:"obj_type"`           // 评论对象类型
	MemberID    uint64 `json:"member_id" form:"member_id"`         // 作者用户ID
	CommentID   uint64 `json:"comment_id" form:"comment_id"`       // 同评论indx_id
	AtMemberIDs string `json:"at_member_ids" form:"at_member_ids"` // at用户ID列表
	Ip          string `json:"ip" form:"ip"`                       // 评论IP
	Platform    uint64 `json:"platform" form:"platform"`           // 评论平台
	Device      string `json:"device" form:"device"`               // 评论设备
	Message     string `json:"message" form:"message"`             // 评论内容
	Meta        string `json:"meta" form:"meta"`                   // 评论元数据 背景 字体
	ReplyID     uint64 `json:"reply_id" form:"reply_id"`           // 被回复的评论ID
	State       uint64 `json:"state" form:"state"`                 // 评论状态 0-正常, 1-隐藏
	RootID      uint64 `json:"root_id" form:"root_id"`             // 根评论id 不为0则为回复一级评论
}

type CommentResponse struct {
	ObjID       uint64 `json:"obj_id"`        // 评论对象ID
	ObjType     uint64 `json:"obj_type"`      // 评论对象类型
	MemberID    uint64 `json:"member_id"`     // 作者用户ID
	CommentID   uint64 `json:"comment_id"`    // 同评论indx_id
	AtMemberIDs string `json:"at_member_ids"` // at用户ID列表
	Ip          string `json:"ip"`            // 评论IP
	Platform    uint64 `json:"platform"`      // 评论平台
	Device      string `json:"device"`        // 评论设备
	Message     string `json:"message"`       // 评论内容
	Meta        string `json:"meta"`          // 评论元数据 背景 字体
	ReplyID     uint64 `json:"reply_id"`      // 被回复的评论ID
	State       uint64 `json:"state"`         // 评论状态 0-正常, 1-隐藏
	RootID      uint64 `json:"root_id"`       // 根评论id 不为0则为回复一级评论
	CreatedAt   uint64 `json:"created_at"`    // 创建时间
	Floor       uint64 `json:"floor"`         //
	LikeCount   uint64 `json:"like_count"`    //
	HateCount   uint64 `json:"hate_count"`    //
	Count       uint64 `json:"count"`         //
}
