// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0-alpha

package types

type CommentListRequest struct {
	ObjID       int64 `form:"obj_id"`                   // 评论对象ID
	ObjType     int64 `form:"obj_type"`                 // 评论对象类型
	PageSize    int64 `form:"page_size"`                // 页大小
	MemberID    int64 `form:"member_id"`                // 作者用户ID
	Cursor      int64 `form:"cursor"`                   // cursor游标 排序时间戳/点赞数
	SortType    int64 `form:"sort_type"`                // 排序方式 0-默认, 1-点赞数, 2-评论时间
	CommentID   int64 `form:"comment_id"`               // offset
	RootID      int64 `form:"root_id"`                  // 根评论ID 不为0则为回复一级评论
	SortedField int64 `form:"sorted_field"`             // 排序字段
	ReplyID     int64 `form:"reply_id" json:"reply_id"` // 被回复的评论ID
}

type CommentListResponse struct {
	List []CommentResponse
}

type CommentRequest struct {
	ObjID       int64  `json:"obj_id" form:"obj_id"`                   // 评论对象ID
	ObjType     int64  `json:"obj_type" form:"obj_type"`               // 评论对象类型
	MemberID    int64  `json:"member_id" form:"member_id"`             // 作者用户ID
	CommentID   int64  `json:"comment_id" form:"comment_id" path:"id"` // 同评论indx_id
	AtMemberIDs string `json:"at_member_ids" form:"at_member_ids"`     // at用户ID列表
	Ip          string `json:"ip" form:"ip"`                           // 评论IP
	Platform    int64  `json:"platform" form:"platform"`               // 评论平台
	Device      string `json:"device" form:"device"`                   // 评论设备
	Message     string `json:"message" form:"message"`                 // 评论内容
	Meta        string `json:"meta" form:"meta"`                       // 评论元数据 背景 字体
	ReplyID     int64  `json:"reply_id" form:"reply_id"`               // 被回复的评论ID
	State       int64  `json:"state" form:"state"`                     // 评论状态 0-正常, 1-隐藏
	RootID      int64  `json:"root_id" form:"root_id"`                 // 根评论id 不为0则为回复一级评论
}

type CommentResponse struct {
	ID          int64  `json:"id"`
	ObjID       int64  `json:"obj_id"`        // 评论对象ID
	ObjType     int64  `json:"obj_type"`      // 评论对象类型
	MemberID    int64  `json:"member_id"`     // 作者用户ID
	CommentID   int64  `json:"comment_id"`    // 同评论indx_id
	AtMemberIDs string `json:"at_member_ids"` // at用户ID列表
	Ip          string `json:"ip"`            // 评论IP
	Platform    int64  `json:"platform"`      // 评论平台
	Device      string `json:"device"`        // 评论设备
	Message     string `json:"message"`       // 评论内容
	Meta        string `json:"meta"`          // 评论元数据 背景 字体
	ReplyID     int64  `json:"reply_id"`      // 被回复的评论ID
	State       int64  `json:"state"`         // 评论状态 0-正常, 1-隐藏
	RootID      int64  `json:"root_id"`       // 根评论id 不为0则为回复一级评论
	CreatedAt   int64  `json:"created_at"`    // 创建时间
	Floor       int64  `json:"floor"`         //
	LikeCount   int64  `json:"like_count"`    //
	HateCount   int64  `json:"hate_count"`    //
	Count       int64  `json:"count"`         //
}
